### ISSUE TITLE
Meow Tutor

### ISSUE THREAD

**Issue by KaranAhlawat** [meow-edit/meow#108]
Hello, great work on meow-tutor! Props to everyone who worked on it.

That said, I think I may have stumbled upon a bug, unless I'm using it incorrectly.

In the More On Beacon section of the tutor, in Example B.
When you grab the line marked by -->, and reverse find for -, pressing c on your selection returns 'No selection'.
This can be reproduced by following the steps outlined in the example.

However, defining a macro yourself using <f3> works as expected, changing all occurences.

This leads me to believe that meow is not starting a recording, and that meow-beacon-change (bound to c in beacon mode) may be bugged.

**Comment by DogLooksGood** [comment]
`'No selection'` means no selection for a command that can only work with a selection. But, by default, `c` should have a fallback behavior when there's no selection.

Did you set `meow-selection-command-fallback`?
The default value is
```
((meow-change . meow-change-char)
 (meow-kill . meow-C-k)
 (meow-cancel-selection . keyboard-quit)
 (meow-pop-selection . meow-pop-grab)
 (meow-beacon-change . meow-beacon-change-char))
```
But `meow-beacon-change` is missed on documentation. I'll add it.

**Comment by KaranAhlawat** [comment]
I have not set `meow-beacon-change`'s fallback manually. 
Since the default is to fallback to `meow-beacon-change-char`, it may be related to that, since it refuses to change the character.

**Comment by DogLooksGood** [comment]
It works for me. so I recorded a gif, can you notice any differences here?
And, are you using the latest version?

![beacon-ex-b](https://user-images.githubusercontent.com/11796018/145174495-994577e0-fcbe-424a-8cdc-712292fc29f4.gif)

**Comment by Linerre** [comment]
> `'No selection'` means no selection for a command that can only work with a selection. But, by default, `c` should have a fallback behavior when there's no selection.
> 
> Did you set `meow-selection-command-fallback`? The default value is
> 
> ```
> ((meow-change . meow-change-char)
>  (meow-kill . meow-C-k)
>  (meow-cancel-selection . keyboard-quit)
>  (meow-pop-selection . meow-pop-grab)
>  (meow-beacon-change . meow-beacon-change-char))
> ```
> 
> But `meow-beacon-change` is missed on documentation. I'll add it.

I came across this problem too while trying out the same example.  
I'm wondering where should users put these config? In their meow's config file?

If I run `C-h f meow--selection-fallback`, I got:

    meow--selection-fallback is a native compiled Lisp function in 'meow-command.el',
    (meow--selection-fallback)

    Run selection fallback commands.

**Comment by eshrh** [comment]
Related to #218, this works now.
