### ISSUE TITLE
Selecting inside quotes

### ISSUE THREAD

**Issue by velppa** [meow-edit/meow#111]
The closest thing to vim's `vi"` (visual inside quotes) I found in meow is `.g` (default QWERTY layout). The idea of `meow-inner-of-thing` and `meow-bounds-of-thing` is great but there are few things with it:
- in some cases it selects more than it should
- doesn't work for arbitrary delimiter, like `vi'`, `vi>` or `vit` (inside tag) works
- having expansion would be helpful, or `meow-block` to select bigger and bigger scope on repeating

Is it expected behavour and if yes then how to achieve "select inside something"?

![meow-select-inside-quotes](https://user-images.githubusercontent.com/480160/145273149-4b1ac8d7-bf96-4e15-b5eb-4e9398108be6.gif)

**Comment by DogLooksGood** [comment]
[meow-thing.el](https://github.com/meow-edit/meow/blob/master/meow-thing.el) contains implementation for all thing-based commands. To register a thing, two functions are require and. 
```
(meow--thing-register 'string #'meow--inner-of-string #'meow--bounds-of-string)
```
The both function returns a cons ( `(beg . end)` ).

And the key -> thing, is defined in `meow-char-thing-table`.

It's easy to implement the bounds-of-string function by reading `(syntax-ppss)`, but it's hard to implement the inner function, because we have no idea what exactly the string delimiter can be.

Yes, we can implement it with the function handle tons of cases, but that is very time consuming.
The solution could be using [tree-sitter](https://tree-sitter.github.io/tree-sitter/). But we won't depend on that directly, since one goal of meow is to be lightweight. 

But if tree-sitter is merged into emacs core, we can rewrite these implementations.
Or there is a suitable package that has functions to borrow, we can let users integration by themselves.

**Comment by velppa** [comment]
Sounds like a good direction, I will try to extend for quotes and tags and send a PR.

**Comment by DogLooksGood** [comment]
That would be really nice. 

Sometimes you probably don't need do the hard work. Meow won't stop you from using other packages. Maybe expand-region is what you want in this case.

**Comment by DogLooksGood** [comment]
I reimplemented thing registration.

For something like `vi>`, 
```
(meow-thing-register 'angle '(regexp "<" ">") '(regexp "<" ">"))
(add-to-list 'meow-char-thing-table '(?a . angle))
```
Should work in the nested structure, in the following case, bounds of angle will select the whole outer one.
```
a < b < c d > e f > g 
                ^ cursor here
```

**Comment by velppa** [comment]
I tried the new meow-thing-register and didn't manage to add new things that are bounded by `SPC`, `"` or `,` the message is "Search didn't not found", if doing re-search-backward manually it works.

Probably it's better to expose a single regexp instead of two for re-search-backward/forward and then user will specify "or" in regexp if needed.

**Comment by DogLooksGood** [comment]
Can you give me some examples about what you are trying to do?

**Comment by velppa** [comment]
This:

```emacs-lisp
  (meow-thing-register 'whitespace '(regexp " " " ") '(regexp " " " "))
  (add-to-list 'meow-char-thing-table '(?q . whitespace))
```

Then `.q` on any symbol in the middle of the string causes: `Search failed: "\\( \\| \\)"` in *Messages*.

**Comment by DogLooksGood** [comment]
I see, looks like you can't have `OR` in regexp with two same branches.

Two regexps is necessary in same situations where you are searching for the matched pair.

For your first example, this will work(with syntax specification):
```
(meow-thing-register 'whitespace '(syntax . " ") '(syntax . " "))
(add-to-list 'meow-char-thing-table '(?q . whitespace))
```

I'll update the implementation to make it support a single regexp.
Thanks for your time!

**Comment by skmd0** [comment]
`.g` no longer seems to be working on version from MELPA. Was there a regression?

**Comment by DogLooksGood** [comment]
There are some changes for meow-thing, but `.g` shouldn't be affected. 

Any reproduce example?

**Comment by skmd0** [comment]
Below is a quick video of trying to do `.g` and nothing being selected. I will try to reproduce it with a clean config.

https://user-images.githubusercontent.com/52122032/145857886-c92d77cc-b02d-4e28-81ba-b9641e2928e9.mp4

**Comment by DogLooksGood** [comment]
Can't reproduce. How about the return value from these two functions `meow--inner-of-string` / `meow--bounds-of-string`.

**Comment by skmd0** [comment]
Here is test from `emacs -q` and fresh install from MELPA.

https://user-images.githubusercontent.com/52122032/145860191-e2f7a0f4-4da0-450a-951c-4aeef7a1bac2.mp4

>How about the return value from these two functions meow--inner-of-string / meow--bounds-of-string.
Not sure how to do that.

**Comment by DogLooksGood** [comment]
Place your cursor inside a string, then `M-: RET (meow--inner-of-string) RET`

**Comment by skmd0** [comment]
```lisp
Debugger entered--Lisp error: (void-function meow-inner-of-string)
  (meow-inner-of-string)
  eval((meow-inner-of-string) t)
  eval-expression((meow-inner-of-string) nil nil 127)
  funcall-interactively(eval-expression (meow-inner-of-string) nil nil 127)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```

**Comment by skmd0** [comment]
The output of that is `nil`

**Comment by DogLooksGood** [comment]
Ohh!

What's your Emacs version.  A few days ago, when I was refactoring meow-thing.el, I fonud emacs has a builtin thing called `string`, So I change the old implementation(search string by syntax-ppss) to use the builtin stuff. 

I guess the `string` is added in some newer version.

**Comment by skmd0** [comment]
`GNU Emacs 27.2` I am on Arch Linux

**Comment by DogLooksGood** [comment]
I'll have a fix by reverting the changes on Emacs 27. Sorry I didn't notice that.

**Comment by DogLooksGood** [comment]
Fixed in c111e74.

Redefine following function should work before you upgrade to a fixed version
```
(defun meow--bounds-of-string ()
  "Return the bounds of the string under the cursor.

The thing `string' is not available in Emacs 27.'"
  (if (version< emacs-version "28")
      (when (meow--in-string-p)
        (let (beg end)
          (save-mark-and-excursion
            (while (meow--in-string-p)
              (backward-char 1))
            (setq beg (point)))
          (save-mark-and-excursion
            (while (meow--in-string-p)
              (forward-char 1))
            (setq end (point)))
          (cons beg end)))
    (bounds-of-thing-at-point 'string)))
```

**Comment by skmd0** [comment]
Tested the master, it works now!

**Comment by velppa** [comment]
Closing the issue since everybody looks happy <3
