### ISSUE TITLE
Org citations and deletion/change

### ISSUE THREAD

**Issue by mclearc** [meow-edit/meow#112]
I've noticed that in org-mode `meow-delete` and `meow-change` don't work as expected inside citation brackets. Say I've got:

`[cite:@beiser1987 chap. 2; @franks2000; @forster2012a; @digiovanni2020]`

placing the cursor after the first bracket and calling `meow-delete` kills the entire line, which is unexpected. Similarly with `meow-change`. Using either of these commands elsewhere within the bracketed citations also deletes the rest of the line. Is this expected behavior? It seems like a bug, but I'm new to meow so... 🤷‍♂️

**Comment by mclearc** [comment]
Yeah --- it seems problematic that this is tied to a keybinding rather than to the actual function, given that different modes will modify this keybinding in different ways (e.g. the function apparently being called in org was `citar-org-delete-citation`). This is going to generate surprises for people. Is there a way to make it so that it just calls `delete-char`?

**Comment by DogLooksGood** [comment]
You can,
- give `C-d` a command to actually delete a char, that's most major modes will do
- or particularly for this case, `(setq meow--kbd-delete-char "<deletechar>")`.

`<deletechar>` is your `Delete` key on keyboard.
