### ISSUE TITLE
Single file release

### ISSUE THREAD

**Issue by DogLooksGood** [meow-edit/meow#120]
Release the whole package in a file, published in the release on Github. Make it easier for people to test with `emacs -Q` or install manually without a package manager.

A list of works need to be done:
- [x] Remove dependencies from meow, like `dash.el`, `s`. Replace their usage with `cl-lib`, which is built-in.
- [ ] Create a script to generate the release file.
- [ ] Update CI

**Comment by Not-Leader** [comment]
why not add a `meow-test.el` file to this repo which can be loaded with `emacs -q -l /path/to/meow-repo/meow-test.el` instead of having it be a single file?

**Comment by DogLooksGood** [comment]
I see a lot emacser manage their configuration by hand, they grab the .el file to their repository.
So a single meow.el will help in this case.

Also, I want to remove(I have already removed in branch ci/remove-deps) dash.el and s.el from this project, make it only depending on built-in packages.

**Comment by DogLooksGood** [comment]
We have removed dependencies, and it's possible to start meow with `emacs -q -L . -l meow.el`. I believe it's enough for now. So close this.
