### ISSUE TITLE
Repeat meow-beginning/end-of-thing

### ISSUE THREAD

**Issue by velppa** [meow-edit/meow#127]
Using `meow-beginning/end-of-thing` and then `repeat` opens a dialog again, but my expectation was that it would repeat without confirmation. The use-case is to "move up by paragraphs", by `[p''''''`. How to approach this, I guess either via using BEACON mode or exposing meow-beginning/end-of-thing as keymaps and then bind functions to they keys here?

**Comment by DogLooksGood** [comment]
What you pointed out is a problem in Meow. Also discussed [here](https://github.com/meow-edit/meow/discussions/101#discussioncomment-1771750).

Adding repeat support for thing commands doesn't make sense. since most of them are not expandable. 
In the previous dicussion, I mentioned a few ideas. Currently, my idea for this purpose is:
```
(meow-normal-define-key
 '("{" . backward-paragraph)
 '("}" . forward-paragraph)
 '("]" . meow-end-of-thing)
 '("[" . meow-beginning-of-thing))

(add-to-list 'meow-char-thing-table (cons ?[ 'paragraph))
(add-to-list 'meow-char-thing-table (cons ?] 'paragraph))
````

To backward select paragraph, use <kbd>[ [ [ [ [</kbd>.
To Forward select paragraph, use <kbd>] ] ] ] ]</kbd>.

How about this? I'm still considering, and I won't make this a default.

**Comment by skmd0** [comment]
I also think it would be great if there was quick way to extand paragraph selection.

What I use right now is:
1. `. p`
2. `;` (optional, if I want to reverse cursor)
3. `M-{` or `M-}` (emacs' native move paragraph keybind)

But pressing all this can be a bit much.

**Comment by DogLooksGood** [comment]
@skmd0 What about my suggestion above? It's available at the moment.

1. You don't have to reverse, the direction of `meow-inner-of-thing`, `meow-bounds-of-thing` are different. `, p` will go forward and `. p` will go backward. Behaviors controlled by variable `meow-thing-selection-directions`.
2. You can have multiple keys mapping to the same thing.

**Comment by skmd0** [comment]
I am just describing how I am personally selecting multiple paragraphs. It maybe helps someone.

Sometimes I press `,` when I wanted `.`, in that case I reverse the cursor with `;`. That's why I added optional.

**Comment by skmd0** [comment]
```elisp
(meow-normal-define-key
 '("{" . backward-paragraph)
 '("}" . forward-paragraph)
 '("]" . meow-end-of-thing)
 '("[" . meow-beginning-of-thing))
```

I think this works really well! 

---

```elisp
(add-to-list 'meow-char-thing-table (cons ?{ 'paragraph))
(add-to-list 'meow-char-thing-table (cons ?} 'paragraph))
```

But I think this is kind of pointless. For example line in thing selection is `l` while in motion is `x`. Probably no need to have 3 character for specifing paragraph.

>How about this? I'm still considering, and I won't make this a default.

Why not add it to pre-defined layouts?

**Comment by DogLooksGood** [comment]
In different keyboard layouts, keys for line are different.  In case for the differences, 
 char <-> thing is mapped by thing name.  I have no idea what is the best, because it depends on how users set their keybindings.
