### ISSUE TITLE
Ediff not using motion mode in some cases

### ISSUE THREAD

**Issue by ktfleming** [meow-edit/meow#130]
When doing `M-x ediff`, the ediff control buffer will be in motion mode, as desired. However, when using ediff to resolve conflicts (for example, calling `magit-ediff-dwim` on a conflicted file in a Magit status buffer), the control buffer will be in normal mode.

I'm not sure why there's a difference there -- it might be something specific to my system, although I don't have much customization of ediff -- but it seems that adding `(ediff-mode . motion)` to `meow-mode-state-list` fixes the problem. Perhaps that should be the default?

**Comment by DogLooksGood** [comment]
Hi, I improved the part about detecting default state in the latest commit.
Have you upgraded yet?

**Comment by ktfleming** [comment]
I upgraded to the latest Meow, and the problem is still there. Doing a bit of debugging, it seems like when doing a normal `ediff`, the "a" key is bound to `ediff-copy-A-to-B` at the time when `meow--enable` runs, and so Meow uses motion mode. However, when running `magit-ediff-dwim`, at the time when `meow--enable` runs, the "a" key is still bound to `self-insert-command`, so Meow uses normal mode. At some point after that (not yet sure when, or how), the "a" key gets bound to `ediff-copy-A-to-C`, but it seems like it's too late for Meow to recognize.

**Comment by DogLooksGood** [comment]
Thank you for investigating, we should add it to `meow-mode-state-list`.

**Comment by DogLooksGood** [comment]
fixed in 6415759
