### ISSUE TITLE
KEYPAD which-key help menu confusion

### ISSUE THREAD

**Issue by skmd0** [meow-edit/meow#134]
This is probably not a bug, but more of a UX issue.

I created an image which shows how pressing `C-c` brings up different which-key information than Meow's keypad `SPC c`

![which-key-difference](https://user-images.githubusercontent.com/52122032/146475090-c81cbd79-1185-4642-832a-df6339181665.png)

The difference is that when you press `C-c` the which-key shows the different keybind in the list, while `SPC c` shows the difference at the very bottom.

Since C- is automatic in keypad mode for each press (unless you press SPC again), it makes sense to hide it in list. But still might be confusing for some people.

This is just a quick observation, feel free to close the issue if it's not that important.

**Comment by DogLooksGood** [comment]
I see, you mean we should show something like `C-c C-`?

![image](https://user-images.githubusercontent.com/11796018/146495704-ab4dd908-f109-4e46-89a8-eba6caa9c9eb.png)

I implement this in branch `improve-keypad-prompt`.

**Comment by skmd0** [comment]
Nice! That is probably be a lot more clear!

**Comment by DogLooksGood** [comment]
After a few days usages, I'd like to revert it, or make it configurable. 

In some cases, it feels pretty annoying,

1) keypad has "fallback" to literal behavior, so not all keys in the popup should be considered as with `C-`

2) you can use backspace to cancel last input. In this case, a tailing `M-` is the last input, but tailing `C-` is not.

**Comment by DogLooksGood** [comment]
With update https://github.com/meow-edit/meow/discussions/190, I think which-key is no longer needed.
The builtin popup will display right after `SPC` is pressed.
