### ISSUE TITLE
Using variables in meow-leader-define-key

### ISSUE THREAD

**Issue by mclearc** [meow-edit/meow#140]
I've defined a variable using `C-c C-SPC` as my personal keybinding prefix key, which I use with `bind-key` for all my personal keybinds. 

```emacs-lisp
(defvar cpm-prefix "C-c C-SPC"
  "Prefix for all personal keybinds")
```

I'd like to use this in `(meow-leader-define-key)` like so:

```emacs-lisp
(meow-leader-define-key
   `("y" . ,cpm-prefix) ;; my namespaced keybindings
)
```

But this won't work. This is likely my fault, but I've tried a variety of things that don't seem to work, so do you know of a way to do this?

**Comment by DogLooksGood** [comment]
Hi, I can't find any problem from your code.

```
(global-set-key (kbd "C-c C-SPC a") #'forward-char)
(global-set-key (kbd "C-c C-SPC b") #'forward-char)

(defvar cpm-prefix "C-c C-SPC")

(meow-leader-define-key
 `("y" . ,cpm-prefix))
```
Above code works on my side.  How you bind your personal keybinds?

**Comment by mclearc** [comment]
Ah -- I had the wrong order of evaluation in the file! Sorry for the noise!
