### ISSUE TITLE
meow-next-expand then meow-grab

### ISSUE THREAD

**Issue by justbur** [meow-edit/meow#143]
First, thank you for the package!

In playing with it for the first time, I noticed one odd behavior. If I use `meow-next-expand` then `meow-grab` the cursor on the first line is offset relative to the remaining cursors. Here's a screenshot
<img width="322" alt="Screen Shot 2021-12-21 at 10 34 23 PM" src="https://user-images.githubusercontent.com/2208382/147031529-3b2bcfdf-f42b-4580-9fbd-ab2cb1d9df8e.png">

Although I can see why this is happened, it seems pretty unexpected to me. I'd like to be able to use `meow-next-expand` then `meow-grab` and get cursors aligned in the same column. Perhaps there is a good reason to keep the current behavior though? 

There's a similar sort of behavior with `meow-prev-expand`.

**Comment by DogLooksGood** [comment]
Yep, it should behavior as what you described. 

Currently, you can select by pressing `meow-line` a few times, instead of expanding by character.
I think I'll have a fix for this recently. So let's keep this issue open.

**Comment by DogLooksGood** [comment]
Should be fixed in the b59840b29cbd1a5ab36aef10e6f4a203db8a5044. 
Please reopen the issue if anything goes wrong.

**Comment by justbur** [comment]
Thank you
