### ISSUE TITLE
meow-global-mode doesn't work pdf-view-mode

### ISSUE THREAD

**Issue by notImposterSyndromeIfImposter** [meow-edit/meow#147]
Context is that I use `org-noter` to annotate and write notes in emacs.  When I execute `org-noter`, I get the below error.  If I disable `meow-global-mode`, I can use `org-noter` and `pdf-view-mode` without issue, but then I can't use your great bindings to write my notes.  To replicate, just open emacs with meow active and call `pdf-view-mode`.

`Error in post-command-hook (meow-global-mode-check-buffers): (wrong-type-argument symbolp (keymap (114 . image-reverse-speed) (48 . image-reset-speed) (45 . image-decrease-speed) (43 . image-increase-speed)))`

I'm using DOOM Emacs with Meow installed via [DOOM Meow](https://github.com/Not-Leader/doom-meow).  Other than this issue everything works perfectly for me.

**Comment by DogLooksGood** [comment]
Hi, this bug had been fixed in a recent commit. Please update the pin.

**Comment by notImposterSyndromeIfImposter** [comment]
Thank you, and my apologies, I didn't realize that.  For anyone else who might be having this issue, I went into 

`~/.doom.d/modules/editor/meow` and edited packages.el to a different commit.  That fixed the problem for me.
