### ISSUE TITLE
emacs becomes unresponsive after meow-search on **

### ISSUE THREAD

**Issue by skmd0** [meow-edit/meow#148]
#### Description
Emacs becomes completely unresponsive when executing `meow-search` on `**`. It doesn't recover, Emacs process has to be killed.

#### Steps to reproduce

1. Input `**`
2. Select it with `meow-next-symbol` (E)
3. Execute `meow-search` (n)

#### Additional information
- GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo version 1.17.4) of 2021-03-26
- Meow version: 20211223.451 (MELPA)

**Comment by DogLooksGood** [comment]
I can not reproduce. 
![image](https://user-images.githubusercontent.com/11796018/147255770-cd5854ec-6d1a-4f65-8651-4de458679b9f.png)
It will search for `\_<\*\*\_>`, and it works. 
What's the content in the buffer?

**Comment by skmd0** [comment]
On my end this can be done in any buffer, but here in video it is demonstrated in `*scratch*`.


https://user-images.githubusercontent.com/52122032/147256986-b8fa8e4b-da8c-4c44-b024-949dd5d8ffae.mp4

**Comment by DogLooksGood** [comment]
Fixed.

**Comment by skmd0** [comment]
Fix confirmed, I tried with version on master. Great job!
