### ISSUE TITLE
Keypad not showing in org mode

### ISSUE THREAD

**Issue by joshcho** [meow-edit/meow#161]
I went through meow-tutor, and for some reason keypad doesn't show in org mode. It shows up fine in emacs-lisp mode and in the tutor.

**Comment by DogLooksGood** [comment]
It's there any errors or messages? Did you mean there's no popup, but the functionality works?

**Comment by joshcho** [comment]
The functionality works, but there's no popup.

**Comment by DogLooksGood** [comment]
It may be a bug. 

I guess you have something in the keymap that can not be parsed by keypad popup.  In this case, some errors should be able to found in *Messages* buffer. Or you can try `SPC m` or `SPC g`, they starts with different keymap. This will prove whether my conjecture is correct or not.

**Comment by joshcho** [comment]
Oh it may be possible I misreferenced the keypad. I meant the numbers that appear below the line when I press 'e' (for expand numbers). These do not appear in org-mode. My apologies for the confusion.

**Comment by DogLooksGood** [comment]
Oh, this behavior is controlled by variable `meow-expand-exclude-mode-list`. 

If you are using monospace font in org-mode, you can remove `org-mode` from this list. Otherwise, the expand hint may mess up the buffer, because every character have different width.

**Comment by joshcho** [comment]
Thank you very much! This package is lovely. I can't wait to incorporate it to my workflow.
