### ISSUE TITLE
`kill-word` messing up beacon

### ISSUE THREAD

**Issue by fbergroth** [meow-edit/meow#163]
Create a buffer containing:
```
abc-123
def-456
ghi-789
```
Enter beacon on each line: `. b G m`. Now, when I press `i M-d <esc>`, I end up with:
```
-123
ädef-456
äghi-789
```
It works as expected if I instead press `<f3> i M-d <esc> <f4>`:
```
-123
-456
-789
```

**Comment by DogLooksGood** [comment]
Reproduced.

**Comment by eshrh** [comment]
Note that using both C-<delete> and M-x kill-word both work. This looks like some problem with how emacs records kmacros... For some reason M-d is getting recorded as [228] instead of [134217828].

**Comment by eshrh** [comment]
Fixed on master. Extremely bizarre bug, see the commit message for details. The main problem is that last-kbd-macro is sometimes a string and sometimes a vector, and converting between the two leads to problems.

**Comment by DogLooksGood** [comment]
Wow!!!! I've spend some time investigating, but have no idea about how to fix.

**Comment by eshrh** [comment]
Yeah, it was very strange, and hard to debug. Took me like an hour of edebug stepping lol
