### ISSUE TITLE
g insert C-M- insted calling command

### ISSUE THREAD

**Issue by krdzo** [meow-edit/meow#164]
When executing this chord `SPC x SPC p g` keypad state enters `C-x p C-M-` but I expect it to call the command that is bound to 
`C-x p g` `(project-find-regexp)`.
There is no `C-M-` prefixed commands under `project-prefix-map` so it should know that there is no ambiguity and insert `g` just like when we don't need to press `SPC` to enter just a _`key`_ when there is no _`C-key`_ binding. Example: insted `SPC x SPC p SPC x` we can enter `SPC x SPC p x` to call `project-execute-extended-command`.

To recreate this is the minimum config:
```
(setq straight-use-package-by-default t)
(straight-use-package 'use-package)

(use-package meow
  :config
  (meow-global-mode 1))

(use-package project)
```
we need Emacs 28 or to download `project.el` from elpa because it has the `C-x p` binding.

**Comment by DogLooksGood** [comment]
Good suggestion! Thank you!

I'll add it.

**Comment by fbergroth** [comment]
Related, I noticed `C-x p m` (`magit-project-status`, available after magit has loaded) couldn't be called via `SPC x SPC p m`.

I also noticed that keymaps are handled different in keypad:
```
(meow-leader-define-key
 '("p" . "C-x p")                       ; SPC p g  doesn't work
 `("P" . ,project-prefix-map))          ; SPC P g  does work
```

**Comment by DogLooksGood** [comment]
It's because the second way are not using keypad. If keypad is used, g will act as `C-M-`(current behavior).

**Comment by DogLooksGood** [comment]
Added.
