### ISSUE TITLE
meow-undo bugged

### ISSUE THREAD

**Issue by joshcho** [meow-edit/meow#165]
I am getting the message "Lisp nesting exceeds 'max-lisp-eval-depth'" on meow-undo, has anyone experienced something similar? Not sure about the conditions that could recreate it.

**Comment by DogLooksGood** [comment]
Hi, You can enable debugging with `M-x toggle-debug-on-error`.
Then post stacktrace here, it may help.

**Comment by joshcho** [comment]
I can't reproduce it at the moment, but I will print the stacktrace if the bug reoccurs.

**Comment by DogLooksGood** [comment]
Okay, reopen when you run into again. 

`meow-undo` is just a plain `undo` after cancel the selection.
