### ISSUE TITLE
meow-char-thing for latex?

### ISSUE THREAD

**Issue by joshcho** [meow-edit/meow#170]
How would you change meow-char-thing-table to support latex fragments? Essentially anything with $$.

**Comment by DogLooksGood** [comment]
Idea 1, register with REGEXP

```
(meow-thing-register 'latex
		     '(regexp "\\$" "\\$")
		     '(regexp "\\$" "\\$"))


(add-to-list 'meow-char-thing-table
	     (cons ?x 'latex))
```

Idea 2, adding support for org-element. Get the range by builtin API.

```
(defun meow-org-element-bounds ()
  (cons
   (org-element-property :begin (org-element-at-point))
   (org-element-property :end (org-element-at-point))))

(meow-thing-register 'org-element
		     'meow-org-element-bounds
		     'meow-org-element-bounds)

(add-to-list 'meow-char-thing-table
	     (cons ?o 'org-element))
```

**Comment by joshcho** [comment]
Added both, thank you!

**Comment by joshcho** [comment]
I

**Comment by DogLooksGood** [comment]
If you use `setq`, put it anywhere you like. But if you use `add-to-list`, that list must be defined, so put it after `(require 'meow)`.

To configure in Elisp, it's better to understand the original APIs instead of all kinds of wrappers(use-package, doom use-package!, leaf, etc).

**Comment by joshcho** [comment]
Thank you, this is incredibly helpful.
