### ISSUE TITLE
meow cursor colors

### ISSUE THREAD

**Issue by mclearc** [meow-edit/meow#176]
Has something changed with the way meow cursor colors are set for each state? I use custom colors, which worked until the last day or so. Right now the faces say that they are set. But all I get is (for a light theme) a black cursor.

<img width="1381" alt="Screen Shot 2022-01-09 at 12 34 22" src="https://user-images.githubusercontent.com/1502422/148693639-894262f5-5e00-4fc8-8feb-6a6ed379db8d.png">

**Comment by DogLooksGood** [comment]
I think it could be a bug introduced with the recent refactor. Apologies, I'll have a fix for this.

**Comment by DogLooksGood** [comment]
fixed.
