### ISSUE TITLE
Binding M-n and M-p in normal mode

### ISSUE THREAD

**Issue by joshcho** [meow-edit/meow#182]
Attempting to bind "M-n" results in the message `Key sequence M-n starts with non-prefix key ESC`. I already use ESC for `meow-cancel-selection`; how can I get both of these behaviors?

**Comment by joshcho** [comment]
I must have screwed with some settings, and it disabled M- keybindings in normal mode. Closing issue.

**Comment by DogLooksGood** [comment]
If you want ESC for meow-cancel-selection, bind `<escape>` instead of `ESC`.

**Comment by joshcho** [comment]
I see, that was the issue. Thank you.
