### ISSUE TITLE
`SPC .` is preferentially translated as `C-c .` 

### ISSUE THREAD

**Issue by vohv** [meow-edit/meow#194]
Even if `SPC .` define as `M .`, `SPC .` still translated as `C-c .`
Easy reproduce in c++-mode.

**Comment by DogLooksGood** [comment]
With the recent update, leader keymap has been removed.  meow-leader-define-key will actually create keybinding in `mode-specific-map`(C-c). And according to keybinding conventions, only `C-c <letter>` is preserved for user.  If you create a keybinding with non-letter, it may cause a confluct.

But, this can be improved, I'm still considering how.

**Comment by DogLooksGood** [comment]
I commit a fix for popup display, now it should show the correct command or keymap.

**Comment by adamkruszewski** [comment]
Populating the default 'global leader' with local mode specific keymap was quite a breaking change for me at least. It definitely overwrote some of my meow-leader-define-keys (like TAB) and as the SPC is hardcoded in meow-keymap.el it is not even that easy to create a separate "clean" global leader key on SPC and move meow-keypad to another key for local mode key mapping. Not complaining, just still trying to figure out how to revert the change.

**Comment by DogLooksGood** [comment]
Hi @adamkruszewski,
I agree with you... we have a discussion here https://github.com/meow-edit/meow/discussions/190
My thought is to revert the behaivor, let user setting a leader keymap. 

At the moment, you can stick with the version 1.3.0, before I make it.

**Comment by adamkruszewski** [comment]
No worries - and thanks, I'll revert to v1.3.0.
