### ISSUE TITLE
Keypad doesn't fallback to `C-c <key> `

### ISSUE THREAD

**Issue by repelliuss** [meow-edit/meow#196]
Starting with cdf5e3056c4dc4ee1384567ea3572c06e305fde9 , keypad doesn't fallback to `C-c <key>` behavior as described in [here](https://github.com/meow-edit/meow/discussions/190).

**Comment by DogLooksGood** [comment]
Are you using doom emacs?
It will fallback to a keymap, by default it's the `mode-specific-map`(C-c keymap). But in doom emacs, C-c is doom-leader-map.

So, you have to add this
```
  (add-to-list 'meow-keymap-alist (cons 'leader doom-leader-map))
```
https://github.com/meow-edit/meow/blob/master/TUTORIAL.org#the-leader-keymap

**Comment by repelliuss** [comment]
No, I don't use Doom Emacs.

To elobarate, after that commit, pressing `SPC l` (nothing bound to that) inserts `l` but after v1.4, it tries `C-c l` as described.

**Comment by DogLooksGood** [comment]
That behavior is depending on the leader keymap. A keymap can let the key pass, or prevent it when no binding is found.
I think I know your case, you have a `C-c l` defined in some map, not the mode-specific-map?

**Comment by repelliuss** [comment]
It is not specific to `l`, it is specific to all letters except letters that have a binding defined by `meow-leader-define-key`. When I inspect with `meow-keypad-describe-key`, the answer is `self-insert-command`. Again, this only happens after https://github.com/meow-edit/meow/commit/cdf5e3056c4dc4ee1384567ea3572c06e305fde9 if related.

**Comment by DogLooksGood** [comment]
If you do `(suppress-keymap mode-specific-map)`, you have the previous behavior.

**Comment by repelliuss** [comment]
But I don't want the old behavior.

I also tested this near to `emacs -Q` state and issue persists.

**Comment by DogLooksGood** [comment]
Sorry, I'm get your point. If you have `C-c a`, and `SPC a` will work, right?

**Comment by repelliuss** [comment]
Yes, it works. But if I don't have, it inserts `a`.  

To sum it up, if I have a definition, let's say for `a`, it works but if I don't have a definition, after https://github.com/meow-edit/meow/commit/cdf5e3056c4dc4ee1384567ea3572c06e305fde9 it inserts `a` but before https://github.com/meow-edit/meow/commit/cdf5e3056c4dc4ee1384567ea3572c06e305fde9 it says `C-c a` is undefined. Is this how it should be?

Another difference is that, when I use `meow-leader-define-key` it works globally for the key before or after as `mode-specific-map` should be. But what I realise now is that, if I have a `C-c a` binding in `prog-mode-map`, that binding works using keypad in programming modes and not others. So it becomes dynamic and I can use my local bindings without any change. But this only works before https://github.com/meow-edit/meow/commit/cdf5e3056c4dc4ee1384567ea3572c06e305fde9 but I don't see why should change after that commit.

For example,

```lisp
(define-key prog-mode-map (kbd "C-c a") #'describe-function)
```

**Comment by DogLooksGood** [comment]
I fixed the usage for `meow-keypad-leader-dispatch`. 

Now it can be either a string like "C-c" or a keymap, or nil(compatible behavior for cdf5e30).

Currently, keypad no longer simulates a C-c prefix, instead it tries to find the keymap based on the value of `meow-keypad-leader-dispatch`.  And, yes, it will fallback to `self-insert-command`, but it's good in MOTION state, since you don't have to remap. If `j` is bound to motion keymap, `SPC j` will still find the original command. If you don't like the behavior, you have to provide a suppressed keymap.

Or any suggestions?

**Comment by repelliuss** [comment]
Thank you, it is clear now.
