### ISSUE TITLE
<BUG> Invalid mode states when using `poly-markdown`

### ISSUE THREAD

**Issue by enderger** [meow-edit/meow#198]
When using `poly-markdown` to have syntax highlighting in Markdown code blocks, it becomes possible for Meow to enter invalid mode states (e.g. both `insert` and `normal` shown at the same time, resulting in one of them being unescapable).
Screen Capture

https://user-images.githubusercontent.com/36283171/153724904-a1cd2f70-de17-4e73-abf8-3a97212761a6.mp4

**Comment by DogLooksGood** [comment]
Hi, it looks like in your video, there's only one state at same moment?

**Comment by enderger** [comment]
Yeah, the bug can have unpredictable results. If you watch the keystrokes,
you can see that leaving a block in insert mode to a buffer in normal mode
prevents the use of insert mode (signalling that the program thinks it
still is in insert mode to some extent). I have seen it show both
indicators, but can’t consistently reproduce that particular variant.

**Comment by DogLooksGood** [comment]
I just made a quick fix, I'm not sure whether it's enough or not. At least, in my case, it works.

**Comment by enderger** [comment]
> I just made a quick fix, I'm not sure whether it's enough or not. At least, in my case, it works.
> 
> How I reproduce the issue: Deleting the tailing ``` then insert it back, it will switch to normal state automatically, which is unexpected behavior. Then move cursor into code block, it will switch to insert state automatically, which is also unexpected.

Seems like that would work, though in my case reproducing it is as simple as entering a code block in normal mode, switching to insert, then using the mouse/arrow keys to escape. I'll test the fix once I figure out how to get it into Nix-managed EMACS.

**Comment by DogLooksGood** [comment]
> entering a code block in normal mode, switching to insert, then using the mouse/arrow keys to escape
I can't reproduce with this.

Can you post a screencast?

**Comment by enderger** [comment]
Seems to be fixed in the latest patch, I'll reopen if it crops up again.
