### ISSUE TITLE
Keybind discrepancy 

### ISSUE THREAD

**Issue by mclearc** [meow-edit/meow#206]
I have the following in my keybindings:

```emacs-lisp
(bind-keys :prefix-map cpm+buffer-keys
           :prefix (concat cpm-prefix " b")
           ("a" . ibuffer)
           ("b" . consult-buffer)
           ("c" . cpm/copy-whole-buffer-to-clipboard )
           ("d" . kill-buffer-and-window             )
           ("e" . cpm/email-save-and-kill            )
           ("E" . erase-buffer                       )
           ("f" . reveal-in-osx-finder               )
           ("i" . ibuffer-jump                       )
           ("j" . cpm/jump-in-buffer                 )
           ("k" . cpm/kill-this-buffer               )
           ("K" . crux-kill-other-buffers            )
           ("m" . consult-global-mark                )
           ("n" . cpm/create-new-buffer              )
           ("N" . cpm/new-buffer-new-frame           )
           ("p" . consult-project-buffer             )
           ("r" . revert-buffer                      )
           ("R" . crux-rename-buffer-and-file        )
           ("s" . consult-buffer-other-window        )
           ("t" . cpm/open-dir-in-iterm              )
           ("[" . cpm/previous-user-buffer           )
           ("]" . cpm/next-user-buffer               )
           ("{" . tab-bar-switch-to-prev-tab         )
           ("}" . tab-bar-switch-to-next-tab         )
           ("<backtab>" . crux-switch-to-previous-buffer)
           ("TAB" . cpm/tab-bar-select-tab-dwim      )
           ("C-M-t" . tab-bar-new-tab                ))
```
the prefix here is `C-c C-SPC` along with ` b`. If I use that key combo them `consult-global-mark` shows up assigned to `m`. But I also bind using `meow-leader-define-key` `SPC b` to the above keymap. However, when I use that latter key combo there is no function assigned to `m`. Any idea why there is this discrepancy between what should be exactly the same maps?

**Comment by eshrh** [comment]
I'm not sure, I tried to repro with
```emacs-lisp
(bind-keys :prefix-map meow-testmap
                 :prefix "C-c C-SPC b"
                 ("m" . (lambda () (interactive)
                    (message "hello world"))))

(meow-leader-define-key
 '("b" . meow-testmap))
```
but it works as expected. How are you binding the prefix to the leader?

**Comment by mclearc** [comment]
I use the following setup:

```emacs-lisp
;;; Personal Keybindings Prefix
(defvar cpm-prefix "C-c C-SPC"
  "Prefix for all personal keybinds.")

;;; Personal Leader Key

(defvar cpm+leader-map (make-sparse-keymap)
  "An overriding keymap for <leader> key, for use with modal keybindings.")

;; Use cpm-prefix as leader namespace
(bind-keys :prefix-map cpm+leader-map
           :prefix cpm-prefix)

;; Use cpm-prefix as leader namespace
(bind-keys :prefix-map cpm+leader-map
           :prefix cpm-prefix)

;;; Meow Setup
(defun meow-setup ()

  ;; Set leader
  (add-to-list 'meow-keymap-alist (cons 'leader cpm+leader-map))
 
more setup...)

(use-package meow
  :straight (:type git :host github :repo "meow-edit/meow")
  :config
  ;; set colors in bespoke theme
  (setq meow-use-dynamic-face-color nil)
  (setq meow-use-cursor-position-hack t)
  ;; Make sure delete char means delete char
  ;; see https://github.com/meow-edit/meow/issues/112
  (setq meow--kbd-delete-char "<deletechar>")
  (setq meow-use-clipboard t)
  (setq meow-goto-line-function 'consult-goto-line)
  (meow-thing-register 'angle '(regexp "<" ">") '(regexp "<" ">"))
  (add-to-list 'meow-char-thing-table '(?a . angle))

  (meow-setup)
  (meow-global-mode 1))
```

**Comment by DogLooksGood** [comment]
Probably because m is for M-? What will happen when press m?

**Comment by mclearc** [comment]
Leader-m (i.e. `SPC-m`) works as expected to initiate a keypad state. So what I suspect is that this is keeping `m` from showing up in my buffer map with leader. But I'm right to think that it shouldn't do this aren't I? The letter `m` should only be reserved for keypad as the first character input after leader is pressed?

**Comment by eshrh** [comment]
To be honest, i'm not too sure what happens when you do `(add-to-list 'meow-keymap-alist (cons 'leader cpm+leader-map)`. While it's true that something like "C-c m" is unreachable from meow leader ("C-m" is irrelevant because "C-m" is RET), the m terminal key is still reachable if it's behind a prefix map, as i showed in my previous comment.

I'm confused by the idea to override the leader itself(i don't think meow-keymap-alist really expects to be changed like that?), what behavior can you not get with `(meow-leader-define-key)`?

**Comment by mclearc** [comment]
> To be honest, i'm not too sure what happens when you do (add-to-list 'meow-keymap-alist (cons 'leader cpm+leader-map).

I wanted to ensure that meow-leader and my map for all my personal keybindings (C-c C-SPC) were the same keybind. Is this not the best way to do that? If not, what is the recommended way (It isn't clear to me from the README & documentation)?

**Comment by mclearc** [comment]
looks like this solves things:

```emacs-lisp
  (setq meow-keypad-meta-prefix nil)
```

 I've gone ahead and set all the `meow-prefix-keypad` keys to nil, since I don't use this shortcut functionality and would rather just bind keys to custom keymaps in a way that produces what I expect.
