### ISSUE TITLE
No expand hints in org-mode

### ISSUE THREAD

**Issue by Calvin-Xu** [meow-edit/meow#219]
I am very new to Emacs so I might be ignorant of some very obvious things, but I'm wondering why expand hints do not seem to appear in org-mode. Meow otherwise seems to work fine. Would be wonderful to know there is something that can enable them.

**Comment by zhscn** [comment]
https://github.com/meow-edit/meow/issues/110#issuecomment-989072886 explains why it is disabled by default

**Comment by Calvin-Xu** [comment]
Ah, I see. Thank you!
