### ISSUE TITLE
Keypad breaks winner-mode

### ISSUE THREAD

**Issue by Svadkos** [meow-edit/meow#227]
If I execute `winner-undo` repeatedly with keypad it just reopens last window and logs new message about growing winner-ring.
```
Winner undo (1 / 20)
Winner undo (1 / 21)
Winner undo (1 / 22)
```

It works properly if I execute `winner-undo` without using keypad.

**Comment by eshrh** [comment]
I don't know how to solve this, but I'll describe the problem if anyone has ideas or wants to solve it.

When you press `SPC c` and wait, a new window is created to show you keys. in [meow-keypad.el:379, ](https://github.com/meow-edit/meow/blob/8cfc0b0ecc03f0a017cf2ec96530c1e5c291394c/meow-keypad.el#L379), we quit the keypad, closing the window before calling the command. However, this closing adds an entry into winner-ring-alist, and so all it does is open the key-description window again.

As expected, it works if you press `SPC c <left>` fast enough for the window to not open. 

There are some options I see.
1. We rewrite keypad to use the minibuffer, but I don't think this is good or necessary.
2. We hardcode meow--keypad-quit to pop off the last two ops in winner-ring-alist.
3. We add a config variable to disable keymap description (doesn't exist, maybe it should?), and you set it to nil
4. We hardcode a shim that adds advice around winner-undo and winner-redo that ignores meow keymap description buffers.

I think 5 is probably the most elegant, 2 is the most likely to work properly, and 3 is the easiest.

**Comment by DogLooksGood** [comment]
Probably 4 is the best idea. Do you have which-key enabled? Will which-key's popup work in this case?

**Comment by Svadkos** [comment]
Which-key has a name for it's buffer. This name can be added to [winner-boring-buffers-regexp](http://www.gnu.org/software/emacs/manual/html_node/emacs/Window-Convenience.html). Which I did, but that didn't solve the problem. Keypad breaks winner-undo even if I use it with which-key.

Also, I don't see any entries for keypad in winner-ring-alist, and I tried to set `meow-keypad-describe-delay` to a higher value and press `SPC c <left>` before keypad window pops up - it didn't work.

FYI i use git version of emacs
GNU Emacs 29.0.50 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.30, cairo version 1.17.4) of 2022-04-24

**Comment by Svadkos** [comment]
Actually, does keypad buffer have any name? Skimming through sources I can't find anything.

**Comment by eshrh** [comment]
my bad, i debugged it wrong because I wasn't familiar with winner mode, my bad. i thought the bug was that the keypad window stayed open, i didn't notice the actual problem. I'll spend some more time with it and get back to you. It might not have a name because it's displayed via `with-temp-message`

**Comment by Svadkos** [comment]
[Here](https://github.com/emacs-mirror/emacs/blob/3af9e84ff59811734dcbb5d55e04e1fdb7051e77/lisp/winner.el#L387-L390), `last-command` seems to be the cause of the bug, but I didn't test if a meow command is always added `last-command` variable, because I don't know how.

**Comment by Svadkos** [comment]
`(setq this-command last-command)` should be added to every interactive command in meow-keypad.el. This solves the problem.

**Comment by eshrh** [comment]
Nice! I feel like meow's reliance on this-command and last-command is a bit impure and has led to issues in the past. Maybe this should be a future target for a refactor. 

Do you want to submit a pull request for this or should I go ahead and commit it?
