### ISSUE TITLE
Question: Beacon mode clarification

### ISSUE THREAD

**Issue by gf3** [meow-edit/meow#237]
Hi there, I'm hoping someone can provide some direction on how to effectively use beacon in the following scenario:

I have this code snippet:

```go
func (ts *PaymentModelSuite) TestCaptureZero() {
	p := &model.Payment{
		DefaultModel: model.DefaultModel{
			IDField: IDField{    // ← Beacon mode
				ID: NewID(), // ← Beacon mode
			},
		},
		StripePaymentIntentID: "pi_abcd",
	}
	err := p.Capture(0, 0)

	ts.NoError(err)
}
```

I enter beacon mode on the two lines marked with `// ← Beacon mode`, I'd like to prepend some text (`model.`) before `IDField{` and `NewID(),`. How do I go about this? When I hit `b` it creates additional cursors but I only want one cursor per line. The final code should look like:

```go
func (ts *PaymentModelSuite) TestCaptureZero() {
	p := &model.Payment{
		DefaultModel: model.DefaultModel{
			IDField: model.IDField{    // ← Beacon mode
				ID: model.NewID(), // ← Beacon mode
			},
		},
		StripePaymentIntentID: "pi_abcd",
	}
	err := p.Capture(0, 0)

	ts.NoError(err)
}
```

Thank you!

**Comment by DogLooksGood** [comment]
For simple case, you probably don't want do `F3/F4`. So just backward till to `:`, then `a C-f model ESC`.

https://user-images.githubusercontent.com/11796018/166980928-4d43fd58-49b5-4b02-bc41-4acd08b4ca46.mp4

**Comment by gf3** [comment]
@DogLooksGood thank you so much! that's incredibly helpful
