### ISSUE TITLE
NORMAL mode not working.

### ISSUE THREAD

**Issue by zenny** [meow-edit/meow#241]
Hi,

I borrowed the configs from https://github.com/DogLooksGood/dogEmacs. I just made changes to init-modal.el as follows:

```
;;; -*- lexical-binding: t -*-

(straight-use-package 'meow)
;; (setq meow-use-dynamic-face-color nil)

(defun meow-setup ()
  (setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)
  (meow-motion-overwrite-define-key
   '("j" . meow-next)
   '("k" . meow-prev))
  (meow-leader-define-key
   ;; SPC j/k will run the original command in MOTION state.
   '("j" . "H-j")
   '("k" . "H-k")
   ;; Use SPC (0-9) for digit arguments.
   '("1" . meow-digit-argument)
   '("2" . meow-digit-argument)
   '("3" . meow-digit-argument)
   '("4" . meow-digit-argument)
   '("5" . meow-digit-argument)
   '("6" . meow-digit-argument)
   '("7" . meow-digit-argument)
   '("8" . meow-digit-argument)
   '("9" . meow-digit-argument)
   '("0" . meow-digit-argument)
   '("/" . meow-keypad-describe-key)
   '("?" . meow-cheatsheet))
  (meow-normal-define-key
   '("0" . meow-expand-0)
   '("9" . meow-expand-9)
   '("8" . meow-expand-8)
   '("7" . meow-expand-7)
   '("6" . meow-expand-6)
   '("5" . meow-expand-5)
   '("4" . meow-expand-4)
   '("3" . meow-expand-3)
   '("2" . meow-expand-2)
   '("1" . meow-expand-1)
   '("-" . negative-argument)
   '(";" . meow-reverse)
   '("," . meow-inner-of-thing)
   '("." . meow-bounds-of-thing)
   '("[" . meow-beginning-of-thing)
   '("]" . meow-end-of-thing)
   '("a" . meow-append)
   '("A" . meow-open-below)
   '("b" . meow-back-word)
   '("B" . meow-back-symbol)
   '("c" . meow-change)
   '("d" . meow-delete)
   '("D" . meow-backward-delete)
   '("e" . meow-next-word)
   '("E" . meow-next-symbol)
   '("f" . meow-find)
   '("g" . meow-cancel-selection)
   '("G" . meow-grab)
   '("h" . meow-left)
   '("H" . meow-left-expand)
   '("i" . meow-insert)
   '("I" . meow-open-above)
   '("j" . meow-next)
   '("J" . meow-next-expand)
   '("k" . meow-prev)
   '("K" . meow-prev-expand)
   '("l" . meow-right)
   '("L" . meow-right-expand)
   '("m" . meow-join)
   '("n" . meow-search)
   '("o" . meow-block)
   '("O" . meow-to-block)
   '("p" . meow-yank)
   '("q" . meow-quit)
   '("Q" . meow-goto-line)
   '("r" . meow-replace)
   '("R" . meow-swap-grab)
   '("s" . meow-kill)
   '("t" . meow-till)
   '("u" . meow-undo)
   '("U" . meow-undo-in-selection)
   '("v" . meow-visit)
   '("w" . meow-mark-word)
   '("W" . meow-mark-symbol)
   '("x" . meow-line)
   '("X" . meow-goto-line)
   '("y" . meow-save)
   '("Y" . meow-sync-grab)
   '("z" . meow-pop-selection)
   '("'" . repeat)
    '("<escape>" . mode-line-other-buffer)))

(require 'meow)
;; ;; (meow-setup)
;;(meow-global-mode 1)
(meow-setup-indicator)

(provide 'init-modal)
```
Despite evaluating the buffer, none of the keybindings appears to work, but reports `j is undefined` and it goes on with everything!

Could not figure out exactly why it is not working?

**Comment by Linerre** [comment]
Hello @zenny,

You just commented out the `(meow-global-mode 1)` line, which is supposed to enable meow. 
The creator's configs for both [qwerty](https://github.com/DogLooksGood/dogEmacs/blob/020763a3377536c2d36bc19cc9936d8cdfdab958/elisp/init-modal-qwerty.el#L92) and [Dvorak](https://github.com/DogLooksGood/dogEmacs/blob/020763a3377536c2d36bc19cc9936d8cdfdab958/elisp/init-modal.el#L158) all have this line uncommented.

The config he's using currently also includes that line, conditionally, though:
https://github.com/DogLooksGood/meomacs/blob/master/editor.org#meow

Could you try to uncomment that line to see if meow works?

**Comment by zenny** [comment]
Hello @Linerre 
> Hello @zenny,
> 
Thanks for your input.

> You just commented out the `(meow-global-mode 1)` line, which is supposed to enable meow. The creator's configs for both [qwerty](https://github.com/DogLooksGood/dogEmacs/blob/020763a3377536c2d36bc19cc9936d8cdfdab958/elisp/init-modal-qwerty.el#L92) and [Dvorak](https://github.com/DogLooksGood/dogEmacs/blob/020763a3377536c2d36bc19cc9936d8cdfdab958/elisp/init-modal.el#L158) all have this line uncommented.

I have tried with the `meow-global-mode 1` which didn't work. So I commented our the line and tried to make it work by manually enabling the micromode (`M-x meow-global-mode`). But no go.
> 
> The config he's using currently also includes that line, conditionally, though: https://github.com/DogLooksGood/meomacs/blob/master/editor.org#meow
> 
> Could you try to uncomment that line to see if meow works?

Already done, but no go. :(

**Comment by Linerre** [comment]
Did you also uncomment the `(meow-setup)` line? This line will make all your keybindings above effective.
And then `(global-meow-mode 1)` enables meow.

It seems you successfully installed meow (via [straight.el](https://github.com/raxod502/straight.el)), since you haven't mentioned any errors saying any `meow-xxx` command is void.

**Comment by zenny** [comment]
> Did you also uncomment the `(meow-setup)` line? This line will make all your keybindings above effective. And then `(global-meow-mode 1)` enables meow.
> 

@Linerre  Thanks that did the trick. Cheers. 

> It seems you successfully installed meow (via [straight.el](https://github.com/raxod502/straight.el)), since you haven't mentioned any errors saying any `meow-xxx` command is void.
