### ISSUE TITLE
bug on meow-*state*-indicator render

### ISSUE THREAD

**Issue by liuyinz** [meow-edit/meow#246]
It seems no matter how I change the faces of six state indicator, they all render with `meow-insert-indicator`
https://github.com/meow-edit/meow/blob/c4b7df0305530da4a51561556794abaf831a228e/meow-util.el#L161-L169

**Comment by Linerre** [comment]
Hi @liuyinz,

Functions and vars that have two dashes in their names are NOT supposed to be used for config. 
They are sort of private to the package itself. 

To change the default indicator txt, check out the var `meow-replace-state-name-list`:

    
    (setq meow-replace-state-name-list '((normal . "N")
                                (motion . "M")
                                (keypad . "K")
                                (insert . "I")
                                (beacon . "B")))
    
Set this variable somewhere before you `(require 'meow)` and enable meow globally via `(meow-global-mode 1)`

**Comment by liuyinz** [comment]
@Linerre  no, I'm talking about faces, not the text. I know it's customizable. I mean indicator faces don't update with state-mode change, only text changes.

**Comment by liuyinz** [comment]
![Kapture 2022-05-16 at 03 14 22](https://user-images.githubusercontent.com/35212403/168490031-f3d5f6a6-e193-461a-80be-3c206785ab19.gif)

**Comment by Linerre** [comment]
> I mean indicator faces don't update with state-mode change, only text changes.

I have updated my comment to include a suggestion for customizing the face

**Comment by liuyinz** [comment]
> > I mean indicator faces don't update with state-mode change, only text changes.
> 
> I have updated my comment to include a suggestion for customizing the face
Gosh.. I know how to customize faces , why not just set different color for state-mode to see what will happen ?

**Comment by eshrh** [comment]
I'm really sorry about that, i didn't see your commit on here before I fixed it myself. We did pretty much the same thing though, it should be fixed on master!

Thanks!

**Comment by liuyinz** [comment]
@eshrh Test OK !
