### ISSUE TITLE
Keybind breakage with :bind-keymap with use-package

### ISSUE THREAD

**Issue by trev-dev** [meow-edit/meow#250]
I am not sure if this is unique to `use-package` or `org-roam` but when I use bind-keymap for org-roam's dailies with meow, the keymap gets stuck turned-on when I type in the opened capture buffer. As such, commands from that keymap keep firing when I press letters  like "d" and "n" while trying to type normal words like "down." This problem goes away when I comment out meow in my config.

Here is how I am set up:

```elisp
(use-package org-roam
  :custom
  (org-roam-directory "~/Org/roam")
  :bind (("C-c r t" . org-roam-buffer-toggle)
         ("C-c r f" . org-roam-node-find)
         ("C-c r i" . org-roam-node-insert))
  :bind-keymap
  ("C-c r d" . org-roam-dailies-map) ; <-- This is the keymap that gets stuck.
  :config
  (require 'org-roam-dailies)
  (setq org-roam-capture-templates td/roam-capture-templates
        org-roam-dailies-capture-templates td/roam-capture-daily)
  (org-roam-setup))
```

**Comment by trev-dev** [comment]
It's worth noting that I was able to replicate this pretty easily with keypad mode. I have stopped using `:bind-keymap` (and use-package). I get tired of unintended side-effects, and I'd rather have a solid go at meow.

**Comment by f7d6c78** [comment]
I am experiencing a similar problem with the package `rg`.

```
(use-package rg
  :ensure t
  :bind-keymap
  ("C-c s" . rg-global-map))
```

Before I press "C-c s" for the first time, using the keypad (SPC c SPC s) won't do anything.
After I use the command with its original keybinding, using the keypad will work as well bit the command will also start firing whenever I press `s` while in the minibuffer, e.g., when typing an interactive function name after `M-x`.

**Comment by DogLooksGood** [comment]
I personally don't use `use-package`. I think it's related to how `autoload` is configured?

I have something like this
```
  (autoload 'rg-project "wgrep" nil t)
  (autoload 'rg-project "rg" nil t)
```

**Comment by huwaireb** [comment]
I'm running into this issue as well, @f7d6c78 could you macro expand on your rg use-package?

@DogLooksGood, 

In one case,
```lisp
(use-package windmove :ensure nil
  :preface
  (defvar-keymap helix/window-map
    :doc "Window Manipulation Keymap"
    "w" #'other-window
    "s" #'split-window-below
    "v" #'split-window-right
    "q" #'delete-window
    "o" #'delete-other-windows
    "h" #'windmove-left 
    "n" #'windmove-down
    "e" #'windmove-up
    "i" #'windmove-right
    "H" #'windmove-swap-states-left
    "N" #'windmove-swap-states-down
    "E" #'windmove-swap-states-up
    "I" #'windmove-swap-states-right)
  :bind-keymap ("C-c w" . helix/window-map))
```

expands to
```lisp
(progn
  (use-package-ensure-elpa 'windmove '(nil) 'nil)
  (eval-and-compile
    (defvar-keymap helix/window-map
      :doc "Window Manipulation Keymap" "w" #'other-window "s"
      #'split-window-below "v" #'split-window-right "q"
      #'delete-window "o" #'delete-other-windows "h" #'windmove-left
      "n" #'windmove-down "e" #'windmove-up "i" #'windmove-right "H"
      #'windmove-swap-states-left "N" #'windmove-swap-states-down "E"
      #'windmove-swap-states-up "I" #'windmove-swap-states-right))
  (defvar use-package--warning34
    #'(lambda (keyword err)
	(let
	    ((msg
	      (format "%s/%s: %s" 'windmove keyword
		      (error-message-string err))))
	  (display-warning 'use-package msg :error))))
  (condition-case-unless-debug err
      (bind-key "C-c w"
		#'(lambda nil (interactive)
		    (use-package-autoload-keymap 'helix/window-map
						 'windmove nil)))
    (error (funcall use-package--warning34 :catch err))))
```

which appears as SPC w : function in which key, not actually working.
C-c w on the other hand, does work.

**Comment by f7d6c78** [comment]
This is what the `rg` `use-package` expands to (I have `elpaca.el` configured with `use-package`):
```
(elpaca rg
  (defvar use-package--warning58
    #'(lambda (keyword err)
        (let
            ((msg
              (format "%s/%s: %s" 'rg keyword
                      (error-message-string err))))
          (display-warning 'use-package msg :error))))
  (condition-case-unless-debug err
      (bind-key "C-c s"
                #'(lambda nil (interactive)
                    (use-package-autoload-keymap 'rg-global-map 'rg
                                                 nil)))
    (error (funcall use-package--warning58 :catch err))))
```

I think the problem is that `use-package-autoload-keymap`  works by accessing `this-command-keys-vector`, which in my case only contains `s`, binds the keymap to it, and then calls `listify-key-sequence` to replay it (which explains why I was experiencing unexpected calls to `meow-kill`).

I'm not an Elisp expert so I'm not sure whether this can be fixed easily, assuming I have identified the issue.
Maybe the keypad functionality could populate the command key vector with the original keybinding keys? No idea if that is possible.
