### ISSUE TITLE
meow-define-state :form hook not triggering

### ISSUE THREAD

**Issue by Calvin-Xu** [meow-edit/meow#252]
Following the documentation for `meow-define-state` in [CUSTOMIZATIONS](https://github.com/meow-edit/meow/blob/b6db7f35d4a664e1e175318e96982fa3688f8264/CUSTOMIZATIONS.org#meow-define-state), I want to just additionally toggle `smartparens-strict-mode` when I enter and leave the example paren state:

```elisp
(setq meow-paren-keymap (make-keymap))
(meow-define-state paren
  "meow state for interacting with smartparens"
  :lighter " [P]"
  :keymap meow-paren-keymap
  :form 'smartparens-strict-mode)
```

However, it seems not to be working. Am I doing something wrong?

**Comment by eshrh** [comment]
I guess this wasn't documented well, but the form should just go in as the last item in the function, no `:form` necessary. If there are an odd number of arguments we interpret the last one as code to run when the mode is triggered. To accomplish what you want you might do

```
(meow-define-state paren
  "paren state"
  :lighter " [P]"
  :keymap meow-paren-keymap
  (smartparens-strict-mode (if smartparens-strict-mode -1 1)))
```
should work.

The form is directly passed to `define-minor-mode` so when the form is called, the mode is already active. This means you can also do some checking on the `meow-paren-mode` to see whether its true, but I'm personally not a fan of this pattern.

**Comment by Calvin-Xu** [comment]
Thank you! This works indeed.
