### ISSUE TITLE
Incorrect behavior when pasting in beacon state

### ISSUE THREAD

**Issue by DogLooksGood** [meow-edit/meow#254]
How to reproduce.
Copy some text, then select the following content, `grab`, `line`, `reverse`, `F3`, `yank`, `F4`.

```
foo
foo
foo
```

**Comment by trev-dev** [comment]
It looks like if you avoid reversing and keep your cursor at the end, you get what's expected:

```
foofoo
foofoo
foofoo
```

**Comment by DogLooksGood** [comment]
Fixed fe0ae35418ca35a48ce2b9bc1cd917ca683620d5
