### ISSUE TITLE
How to escape keypad-mode with a single C-g?

### ISSUE THREAD

**Issue by ml729** [meow-edit/meow#264]
Hello, right now it takes two presses of `C-g` to exit `keypad-mode` for me. (for instance, I press `SPC x` to enter keypad mode, but after pressing the first `C-g` I am still in keypad mode.) Is it possible to get meow to exit keypad mode with a single `C-g`?

I have tried binding `C-g` to `meow-keypad-quit` in ` meow-keypad-state-keymap` (using Doom's `map!` macro) but this does not work. But binding other keys such as `C-k` to `meow-keypad-quit` does work, it is only `C-g` with this issue. Thanks.

**Comment by DogLooksGood** [comment]
It could be bug in Meow's default keypad popup. Currently, you can enable `which-key-mode`(which will replace the default popup menu).

**Comment by ml729** [comment]
Thanks. It does seem to be an issue with the popup. Specifically in the definition of `meow-describe-keymap` [here](https://github.com/meow-edit/meow/blob/ca4f781cef271fe8affc206d0cd9cfce426e63c1/meow-keypad.el#L311), I am guessing the first C-g ends up cancelling the `sit-for` that is running? When I replace `with-temp-message` with `message` (and remove the `sit-for` call) the issue goes away. (However when I do this, for some reason I need to manually setq `max-mini-window-height` to `1.0` to get the window height to not be truncated.) I'm curious if there is an advantage for using `with-temp-message` with `sit-for` for 1,000,000 seconds instead of using `message`.

Also, regarding `which-key`, I tried running `(meow--setup-which-key t)`. The result is after pressing some prefixes such as `SPC x` and `SPC h`, I get the error "Two bases given in one event" and no popup appears. But then after pressing the next key in the command (like SPC, k, etc.), the which key popup is shown correctly. But indeed, when using which-key, a single `C-g` exits keypad-mode.

**Comment by DogLooksGood** [comment]
Solved somehow.
