### ISSUE TITLE
`meow-line` incompatibility with GNU Hyperbole

### ISSUE THREAD

**Issue by grszkthfr** [meow-edit/meow#269]
I recently tried [GNU Hyperbole](https://www.gnu.org/software/hyperbole) and found that `meow-line` does not work when it is installed (`mark: The mark is not active now`)

This is reproducible following the installation instructions [here](https://github.com/meow-edit/meow/blob/master/GET_STARTED.org#try-without-installation=) and [here](https://www.gnu.org/software/hyperbole/#installation) in an `emacs -Q` session (Emacs 28.1). Before the Hyperbole installation, `meow-line` works as expected, after the installation it returns the message above. Might be related to #235.

As I haven't decided whether I want to use GNU Hyperbole or not, this issue has no priority for me. I just leave it here, in case it might be relevant for someone else.

**Comment by ragreenburg** [comment]
Just had this same issue, and was confused how this hadn't been noticed.

**Comment by eshrh** [comment]
Is the error fixed if you change `(mark)` to `(mark t)` in https://github.com/meow-edit/meow/blob/10cae35366758cf018c1f3cb6cb0c81087da079e/meow-command.el#L881

like it was suggested in #235? If it is, then i'll probably just push that change.

**Comment by ragreenburg** [comment]
> Is the error fixed if you change `(mark)` to `(mark t)` in
> 
> https://github.com/meow-edit/meow/blob/10cae35366758cf018c1f3cb6cb0c81087da079e/meow-command.el#L881
> 
> like it was suggested in #235? If it is, then i'll probably just push that change.

That sure does fix it! I went it, made the change, ran `eval-buffer`, restarted Emacs, and it works!

**Comment by eshrh** [comment]
awesome, i just pushed it to master.
