### ISSUE TITLE
meow-search counter bug

### ISSUE THREAD

**Issue by zhscn** [meow-edit/meow#270]
<img width="93" alt="image" src="https://user-images.githubusercontent.com/45552541/175816885-a46c930a-2390-40bf-9df9-bd97879b3cd2.png">
how to reproduce:

1. insert `foo`
2. `meow-mark-word` select `foo`. [1/1]
3. enter insert mode, insert another `foo`
4. return normal mode, `meow-mark-word` select `foo` [2/1]

**Comment by eshrh** [comment]
it seems like there are serious issues with the cache mechanism in `meow--highlight-regexp-in-buffer`. To be totally honest, I'm no so sure what was the intended behavior with the caching, It works fine with files that you are not changing much, but breaks when you modify the buffer.

https://github.com/meow-edit/meow/blob/70c27de889260b809a4f1010b3ce9c21bac5f87b/meow-visual.el#L117-L129

What really confuses me is that if you mark the same word twice, then even in the caching cond branch(linked above) we still re-search-forward through the entire file as far as I can tell. I don't think there's any performance benefit at all here.

Issues are pretty clear for example if you insert `foo` 5 times, delete all but one, mark it, you will see `[4/5]` with the current code. I'm actually surprised that nobody noticed this sooner.

I'll commit a quick hotfix to always regenerate cnt and idx to master. Please leave this issue open until @DogLooksGood gets a chance to look at it.

**Comment by DogLooksGood** [comment]
Ah, I knew this already.
