### ISSUE TITLE
Stuttering with meow-next

### ISSUE THREAD

**Issue by trev-dev** [meow-edit/meow#278]
In certain, large buffers, I am seeing a performance hit while holding down "j" (`meow-next`) to scroll down the page. The emacs binding of `C-n` for `<down>` does not seem to have this problem. I have so far seen this in large-ish buffers like my org configuration file and  200kb Guile Scheme file.

**Comment by eshrh** [comment]
i can't seem to replicate this. I used this:
```python
f = open("largefile.txt", "a")
for i in range(100000):
    f.writelines(["abcabcabcabcabcabc\n"])
```
to make a ~2mb, 100k line file, and i don't see any stutter at all. my emacs version is 29.0.50.

https://github.com/meow-edit/meow/blob/10cae35366758cf018c1f3cb6cb0c81087da079e/meow-command.el#L619-L634

we're not doing too much before calling the macro for C-n. 

could you take a cpu profile? Call `profile-start`, call meow-next several times, and call `profile-report`.

**Comment by trev-dev** [comment]
Of course now that I've submitted an issue and come back to it several hours later, I can't replicate it. Until I can, I will close this.

**Comment by trev-dev** [comment]
Wait, I got it.
[meow-profile.log](https://github.com/meow-edit/meow/files/9078982/meow-profile.log)

**Comment by trev-dev** [comment]
I removed the magit features from my modeline for a day while working on the same files, meow seems to keep up OK. I will find some other, hopefully simpler way to check if my git workspace is "dirty"

**Comment by trev-dev** [comment]
Unfortunately my slimmer git function for the modeline is still tripping up in Meow normal mode. Probably because some aspect of Meow is requiring a modeline update somehow. This doesn't happen by simply keying "next-line"

![Screenshot from 2022-07-17 15-17-06](https://user-images.githubusercontent.com/28788713/179426875-30a0acfa-c48b-4d70-897e-568b877e2ee0.png)

I see something to do with beacon mode is also happening here. Beacon is not (currently) active.

**Comment by DogLooksGood** [comment]
![image](https://user-images.githubusercontent.com/11796018/179428301-e96db61b-c9ba-4405-9378-2a9c7c781c35.png)
My profiler report after holding `meow-next` for a while.

**Comment by trev-dev** [comment]
Yeah I don't think this is going to be an easy one to replicate and catch. At some point while using meow, things get confused and `meow-next` starts triggering side-effects.

**Comment by trev-dev** [comment]
Here's what meow does with me after a clean re-start of emacs. Whatever thing I am doing to trigger the need to update the modeline over-and-over again has not yet happened.

![Screenshot from 2022-07-18 09-22-58](https://user-images.githubusercontent.com/28788713/179557450-1d047bd4-e00f-4582-8831-9b5f4a7b0f95.png)

**Comment by trev-dev** [comment]
Hey, so I have a meaningful update. I was stuttering again with meow-next and noticed multiple calls per next line to update my modeline.

I examined which modes were active. **Beacon mode was still on** despite my having been done with it quite a while ago in that buffer.

I turned off beacon mode & meow-next was nice and smooth again.

Can we think of any reason how beacon mode might get left on?

**Comment by trev-dev** [comment]
I have removed meow-beacon-mode from my diminished modes so I can spot it from now on. Perhaps it's best to not assume this is a bug for now.

**Comment by trev-dev** [comment]
Just as a note for anyone curious about this, the culprit was _still_ the vc modeline functions. Even after simplifying it.

With some help from the illustrious @yantar92, I implemented a rate-limiting implementation:

```elisp
(defvar tdm/git-cached-status nil)
(defvar tdm/git--last-update nil)

(defun tdm/git-dirty? ()
  "Return t if local repository is dirty."
  (if (and
       tdm/git--last-update
       (< (float-time
           (time-subtract (current-time) tdm/git--last-update))
          1.0))
      tdm/git-cached-status
    (setq tdm/git--last-update (current-time))
    (setq tdm/git-cached-status
          (with-temp-buffer
            (vc-git-command t 0 nil "status" "--porcelain")
            (> (buffer-size) 0)))))

(defun tdm/vc ()
  (when-let (vc vc-mode)
    (format "[%s]" (propertize
                    (substring vc 5) 'face (if (tdm/git-dirty?)
                                                    'warning
                                                  'success)))))

```

I have not had problems since.
