### ISSUE TITLE
Meow starts in motion mode in the calc buffer.

### ISSUE THREAD

**Issue by trev-dev** [meow-edit/meow#292]
I tried evaling `(add-to-list 'meow-mode-state-list '(calc-mode . normal))` but it did not seem to have any effect.

**Comment by eshrh** [comment]
I'll take a closer look at this issue in a little while, but it would appear that calc never calls meow--enable, and so the meow-mode-state-list isn't checked.

**Comment by trev-dev** [comment]
Well, it is working now, and I'm sure you've changed nothing. What's more is you're right, I _can_ punch numbers in motion mode. Not sure why I struggled with this today. Thanks for looking :)
