### ISSUE TITLE
meow能设定初始为insert-mode吗

### ISSUE THREAD

**Issue by nick357** [meow-edit/meow#307]
在写文件多的场景下，初始 normal-mode 不是很方便。希望能提供初始为 insert-mode 的方案。

**Comment by Linerre** [comment]
Meow 的主要特点就是在 normal-mode 下更高效地把 selection 和 movement 结合起来了，所以大多时候 normal-mode 是默认的。一些 mode （e.g. dired-mode) 里 Motion 更合理。这是两种推荐的初始模式。

这里有人问过相似的：https://github.com/meow-edit/meow/discussions/286

硬要做也完全可以，在 Meow 的配置里设置 `mew-mode-state-list`: https://github.com/meow-edit/meow/blob/master/CUSTOMIZATIONS.org#meow-mode-state-list

但是我个人更倾向于遵循包的设计初衷。你这个场景如果特别依赖 insert-mode, 倒不如写个 lambda 或者快捷键来方便的 enable/disable `meow-mode`:
```
(add-hook 'some-mode-hook (lambda () (meow-mode -1)))
```
毕竟 Meow 与 Emacs 的原生按键不冲突，如果长时间在 insert-mode 下用 Emacs 的话，倒不如关了 Meow, 直接用 Emacs 开始编辑

**Comment by nick357** [comment]
受到你的启发，用下面的hook是能实现的，多谢！
(add-hook 'meow-mode-hook (lambda () (meow-insert-mode)))
