### ISSUE TITLE
Customized meow-search-highlight foreground

### ISSUE THREAD

**Issue by trev-dev** [meow-edit/meow#310]
Can anyone reproduce this bug where I have explicitly set the foreground for meow-search-highlight, but said highlight is being ignored?
![highlight](https://user-images.githubusercontent.com/28788713/186695047-083af57b-62b4-4adb-9110-236b6c6e5d2b.png)

![ignored](https://user-images.githubusercontent.com/28788713/186695350-0172d24d-115c-47c3-8209-c55e0bb59d90.png)

**Comment by eshrh** [comment]
Doesn't that look right? the background is the same shade of brown...right?

**Comment by DogLooksGood** [comment]
meow has dynamic color calculation, you can disable it, then custom each faces.

**Comment by trev-dev** [comment]
Sorry guys what the screen shots are missing is I have explicitly set the :foreground to "#EEFFFF"

I will look at the dynamic color settings. If need be I will writr first-class support for Meow into the theme

**Comment by trev-dev** [comment]
Even if I set `meow-use-dynamic-face-color nil` the foreground color stubbornly stays `nil`.

**Comment by trev-dev** [comment]
Stale.
