### ISSUE TITLE
KEYPAD hint

### ISSUE THREAD

**Issue by drcxd** [meow-edit/meow#316]
I just noticed that the short-cut hint messages provided by using KEYPAD is not the same as which-key. I observed that which-key opens another window to display the hint messages, while meow KEYPAD does not. Could meow KEYPAD do the same thing as which-key or delegate the work to which-key?

I am asking this because the current KEYPAD hint information is truncated by another package https://github.com/kiennq/emacs-mini-modeline. which-key hint can be displayed correctly, but meow KEYPAD hint can not.

Which-key:
![image](https://user-images.githubusercontent.com/24535087/187658379-8a8531ee-c0af-4a6e-b60c-0d42e9ed7c95.png)

Meow KEYPAD:
![image](https://user-images.githubusercontent.com/24535087/187658512-e8a743f3-33ad-490f-a04c-ffeb74b54a9a.png)

In addition, this behavior happens only after invoking the vertico completing system.

**Comment by drcxd** [comment]
I found this issue is happening because I enabled which-key-mode before I setup meow, so `meow--which-key-describe-keymap` is not invoked properly. After adjust the initialization sequence, the issue is solved.

However, the thing-help information still is displayed in the echo area, could it use which-key as well?

**Comment by DogLooksGood** [comment]
Good to know you find the problem yourself. No, thing-help information is different, can not have it in which-key.
Because it's not keymap based.
