### ISSUE TITLE
PAIR-EXPS don't work when the start and end token is the same

### ISSUE THREAD

**Issue by pRot0ta1p** [meow-edit/meow#321]
When the start token and end token for PAIR EXPS is the same, `meow-thing-register` can't create a actual funtional pair thing.

For example, for creating a pair matching double qoutes:
```elisp
(meow-thing-register 'qoute
                     '(pair ("\"") ("\""))
                     '(pair ("\"") ("\"")))
```
will actually match nothing.

**Comment by DogLooksGood** [comment]
You have to use either FUNCTION or REGEXP in this case.

**Comment by pRot0ta1p** [comment]
I'll settle with REGEXP then, though I miss PAIR EXPR's ability to select only matched pair.

**Comment by DogLooksGood** [comment]
PAIR EXPR is for nested structure. For example, in this case:

`do do end | do end end`
Meow will know the first `end` is not the end of this block.

**Comment by pRot0ta1p** [comment]
Ah, now I understand, delimiters like quotes don't nest and therefore not suited for PAIR EXPR, thanks for clarifying.
