### ISSUE TITLE
Could meow support multi selection beacon ?

### ISSUE THREAD

**Issue by XaydBayeck** [meow-edit/meow#328]
In [helix](https://helix-editor.com/), when I select one or more lines, I can press 's' and then input a pattern to select every block match the pattern I input.

I think this is a very good function, but meow seems lack it.

So, I hope to add an ability in meow: I can use a any motion to select a block then press key bind to `meow-repeat-grab` to repeat the motion and add a fake cursor behind of the new selected block.

**Comment by DogLooksGood** [comment]
There's a similar one, use `mark-word` or `mark-symbol` in the secondary selection. Then you got all samething selected. 
With real example, it's easier to explain how to use it.

**Comment by XaydBayeck** [comment]
Sorry, I didn't see the [explanation](https://github.com/meow-edit/meow/blob/master/EXPLANATION.org) section.
I've been found the answer in it. Thanks.
