### ISSUE TITLE
Meow cut copy and paste not woriking with Windows Clipboard

### ISSUE THREAD

**Issue by samwdp** [meow-edit/meow#330]
The commands meow-kill meow-yank and meow-save do not work with Windows clipboard. The default emacs kill-ring does work though so in order to copy from emacs with the inbuild meow I would have to use kill-ring-save and yank. Is there any way to get the meow commands to work with the windows Clipboard?

![copy-paste](https://user-images.githubusercontent.com/7193913/190995649-1c3a951c-793a-4f59-8fea-ca4d529deca5.gif)

**Comment by DogLooksGood** [comment]
There's a variable `meow-use-clipboard`.

But it's recommand to not mix emacs kill-ring and system clipboard.
