### ISSUE TITLE
Control-[ doesn't exit insert state in GUI Emacs

### ISSUE THREAD

**Issue by tim-mccarthy** [meow-edit/meow#336]
As far as I understand, `C-[` should be equivalent to `ESC`, but when I try to use it to get back to normal state in meow on a GUI Emacs (28.1, installed through Nix, tested on macOS and Ubuntu), I just get an `ESC-` prompt in the minibuffer as if I was using it as a Meta prefix. `ESC` itself works fine.

In a terminal with `emacs -nw`, both work.

My configuration consists entirely of `straight.el` bootstrapping code and the default meow config for QWERTY layout.

**Comment by DogLooksGood** [comment]
Well, in GUI, "<escape>" and "ESC" are different.

**Comment by tim-mccarthy** [comment]
Ah, I see! The solution was as simple as

``` 
(meow-define-keys 'insert
   '("ESC" . meow-insert-exit))
```

Thanks!
