### ISSUE TITLE
No way to start meow keypad with meta already pressed

### ISSUE THREAD

**Issue by corytertel** [meow-edit/meow#342]
I cannot find a way to start the meow keypad with meta already pressed. 

I have tried:
`(meow-keypad-start-with "M-")`
`(meow-keypad-start-with "M")`
`(meow-keypad-start-with "m")`
`(meow-keypad-start-with "meta")`

I looked into the source code but do not see an obvious way to start the keypad like this.

To be clear the state I wish to start the keypad in is the same state obtained by `SPC m`.

**Comment by DogLooksGood** [comment]
Do I understand correct? You want input `SPC <letter>` be translated to `M-<letter>`?

**Comment by DogLooksGood** [comment]
You can find the keymap activated after `ESC`(Which is the same with Meta pressed) by 
```
(lookup-key global-map (kbd "ESC"))
```
It's called `ESC-prefix`.

So, we can do
```
(setq meow-keypad-leader-dispatch 'ESC-prefix)
```

**Comment by corytertel** [comment]
I should have clarified further. I do not wish to change the leader dispatch permanently. I still want `SPC` to bring up the keypad with nothing pressed (the default behavior). I'm looking to create a function that will bring up the keypad with meta already pressed, similar to god-mode behavior. 

With your help I now have this.
```lisp
(defun meow-keypad-meta ()
    (interactive)
    (setq meow-keypad-leader-dispatch 'ESC-prefix)
    (meow-keypad))

  (defun meow-keypad-normal ()
    (interactive)
    (setq meow-keypad-leader-dispatch nil)
    (meow-keypad))
```

With `meow-keypad-normal` bound to `SPC` and `meow-keypad-meta` bound to `m`. 

While this works, I'm curious if there's a better solution to this.

**Comment by corytertel** [comment]
Also, `(meow-keypad-start-with "ESC")` seems like it should work, but not all my custom set keybinds are available in the menu.

**Comment by DogLooksGood** [comment]
Could you show an example?

**Comment by corytertel** [comment]
I believe that `(meow-keypad-start-with "ESC")` only shows globally set keybinds because the escape map only shows globally set keybinds. Upon further testing it seems that my `meow-keypad-meta` defined above is victim to the same thing. Here's an example.

This is the menu for when the key sequence `SPC m` is pressed in normal mode, which perfectly simulates meta.
![2022-10-08_06-37](https://user-images.githubusercontent.com/60120648/194710748-51e4dd55-5ac8-4421-84f3-19ce553e3030.png)

This is the menu for when `(meow-keypad-start-with "ESC")` is run.
![2022-10-08_06-38](https://user-images.githubusercontent.com/60120648/194710763-ccb48fa6-4d0c-4cf5-ba72-edd095acfbe8.png)

The former shows all avaliable keybinds whereas the latter only shows global keybinds.
Is there any way to launch the keymap immediately into the same state that the keymap is in after `SPC m` is pressed?
