### ISSUE TITLE
Multi-cursors not displaying

### ISSUE THREAD

**Issue by rynoV** [meow-edit/meow#343]
Hi, thanks for making this!

Multiple cursors aren't being displayed for me. For example:

![2022-10-08-124906_112x87_scrot](https://user-images.githubusercontent.com/35615725/194723033-156db405-f5b8-4bd3-924a-80ffc3701b9f.png)

This is what I see after selecting three lines and running `meow-grab`, but I expected there to be cursors shown at the end of each line, as shown in [the explanation document](https://github.com/meow-edit/meow/blob/master/EXPLANATION.org). Following the key sequences from that document works for me though, so it seems the multi-editing is working but I'm just not getting visual feedback.

Any help is appreciated. I'm using Emacs 28.2. Let me know if you need any more info :)

**Comment by DogLooksGood** [comment]
By default, meow will calculate faces for these cursors. which theme you are using?

**Comment by rynoV** [comment]
@DogLooksGood I'm using https://github.com/doomemacs/themes/blob/master/themes/doom-nord-theme.el

**Comment by rynoV** [comment]
For some reason when I load the theme for a second time (`(load-theme 'doom-nord t)`) the cursors start to show up. However they still don't always show up when they're at the end of the lines.

**Comment by rynoV** [comment]
Are there faces I can change manually for these cursors? Modifying `meow-region-cursor-1/2/3` doesn't seem to do anything

**Comment by DogLooksGood** [comment]
You have to disable dynamic faces first. 
```
(meow-use-dynamic-face-color nil)
```

**Comment by DogLooksGood** [comment]
This should be useful to find all dynamic faces. But doom-nord works in my case, it's weird.
