### ISSUE TITLE
`SPC RET` does not run `org-insert-heading-respect-content` in org-mode

### ISSUE THREAD

**Issue by ParetoOptimalDev** [meow-edit/meow#344]
Instead it runs command `newline`.

In the tutorial's [keypad section](https://github.com/meow-edit/meow/blob/master/TUTORIAL.org#keypad) it says:

```
Any other <key> will be translated to C-<key>.
```
My understanding was `SPC RET` would equate to `C-RET` which in org mode is `org-insert-heading-respect-content` by default.

**Comment by eshrh** [comment]
same issue as #338.

The docs are somewhat context dependent here. It means that any other keys /after a prefix/ get modified with `C-`. So like `SPC x f -> C-x C-f`, which is the example in the emacs tutor.

In your case, SPC RET gets looked up in the `mode-specific-map`, probably `C-c`, so it calls `C-c RET`

I've just rewritten this section in d180d47c56ec06d054fb101bc843340d93c26d41. Hopefully this clears things up.

**Comment by ParetoOptimalDev** [comment]
Alright, so I read the new docs as saying "there is no way to use KEYPAD to get `C-RET` so long as `C-c RET` is bound in the org-mode-map.

So my options are to define mode specific bindings maybe or to just keep using the emacs binding `C-RET`.

**Comment by aminevsaziz** [comment]
> same issue as #338.
> 
> The docs are somewhat context dependent here. It means that any other keys _after a prefix_ get modified with `C-`. So like `SPC x f -> C-x C-f`, which is the example in the emacs tutor.
> 
> In your case, SPC RET gets looked up in the `mode-specific-map`, probably `C-c`, so it calls `C-c RET`
> 
> I've just rewritten this section in [d180d47](https://github.com/meow-edit/meow/commit/d180d47c56ec06d054fb101bc843340d93c26d41). Hopefully this clears things up.

I was looking for a solution for similar issue (`C-;`) and from this post, I figure out @eshrh that there no solution. simply adding more keybinding to my config or keep using `C-` . surprisingly, God-mode does support the `SPC-;` = `C-;`

**Comment by DogLooksGood** [comment]
By default, `SPC` is bound to `meow-keypad-start`. So when you hit `SPC`, meow enters KEYPAD state from NORMAL/MOTION state.

Now, there are two cases:
- If the next key is in `meow-keypad-start-keys`, `meow-keypad-meta-prefix`, `meow-keypad-ctrl-meta-prefix`, the input will be translated, and all following keys will be translated as well.
- If the next key is not in these keys, the input will fallback to leader behavior, by default, it's `mode-specific-map`. Then following keys will be translated.
