### ISSUE TITLE
How to enable a keymap when in insert mode

### ISSUE THREAD

**Issue by Kenneth-Mata** [meow-edit/meow#348]
I use vertico, i usually have 
``` lisp
(keymap-set xah-fly-keys-insert-mode-map kbd "C-j" #'vertico-prev)
(keymap-set xah-fly-keys-insert-mode-map kbd "C-l" #'vertico-next)
```
but trying the same with meow-insert-state-keymap doesn't seem to work, i also tried 
``` lisp 
(meow-define-keys
 'insert
 '("C-j" . vertico-prev))
``` 
without success

**Comment by DogLooksGood** [comment]
I think you should define key in `minibuffer-mode-map`. Meow doesn't affect minibuffer.

**Comment by Kenneth-Mata** [comment]
thank you, it worked
