### ISSUE TITLE
Staying in Keypad mode after entering a full command?

### ISSUE THREAD

**Issue by RKBK** [meow-edit/meow#356]
First of all, thanks for making a very impressive and useful addon to Emacs. This is the first of a few questions I have about meow-mode usage.

I previously used god-mode extensively. The Keypad mode in meow does some of the same work that god-mode did. However, one feature I really appreciated in god-mode is that you stay in god-mode (where e.g. pressing `c` gives you `C-c`) until you manually disable it e.g. by pressing Esc. The advantage of this behavior is that god-mode did a lot of the work that a full modal editing framework allows. You could press `n` and `p` to navigate up and down, `a` and `e` to go to beginning and end of line, `c c` to get `C-c C-c`, and so on. 

Now that I'm using meow-mode, I find myself missing this behavior. It's true that the meow normal-mode does give you the ability to do most of the things I mentioned above. However, some things take longer (require more key presses) in meow than they would in god-mode. For example, as far as I've been able to understand, go to beginning of line becomes `x ;` in meow, but would have been just `a` in god-mode. This is an example of the normal-mode in meow being less efficient than god-mode. Invoking `M-o` (my shortcut to switch between windows in a frame) is `g o` in god-mode, but becomes `SPC m o` in meow. It's true that I first have to switch to god-mode with Esc, but once I was in god-mode I usually spent a bit of time in this mode, just e.g. navigating the buffer. With meow, I have to prefix every single command with SPC. This is an example of Keypad mode being less efficient than god-mode. Furthermore, some of the most simple shortcuts (e.g. `C-a` to go to beginning of line) aren't triggered by Keypad mode at all.

The issue is basically that having to invoke Keypad mode with SPC for every "god-mode-like" command you want to invoke is extra work. Another way of describing the issue is that with god-mode, I was able to pretty much not ever keep C or M pressed when entering commands, but now with meow-mode I find myself having to press them frequently. 

It would be nice if there was a way to stay in Keypad mode once you're there. I guess either through using a setting where you have to manually exit Keypad mode with Esc, or perhaps by having a separate command to invoke a "sticky Keypad mode".

**Comment by DogLooksGood** [comment]
Hey, there are some points.

1. An alternative to the sticky god-mode for keybinds those started with `C-c`, `M-`, and more. This setup helps.
```
(meow-normal-define-key
 '("c" . meow-keypad-start)
 '("x" . meow-keypad-start))
```
2. You rarely want to go to the beginning of line, most of the time, you want to do something at the beginning of the line, for example, insert. Then you use `meow-line`, then `meow-insert`. Once you have the selection, actually you got two positions at the same time: end beginning and the end.
3. To elaborate previous point a little bit more, the same work can be done in meow in a different approach. For example(`|` represents the cursor). If you want to select till the end of the "three" in the second line, in a traditional thinking, you keep selection activated, go to the second line, then move forward by two words. In meow, you describe your purpose in a single command, because you want to select to the end of a word, then you do `next-word`, you will see the number hints, then you jump with numbers. You need some meow-way thinking, otherwise some work can't be done easily.
```
one |two three four ...
one two three four
```

**Comment by RKBK** [comment]
Thanks for your replies! I'll try your suggestions (here and on the other two issues) and see if it clicks for me.

**Comment by RKBK** [comment]
I understand points 2 and 3, thanks for the clarification.

Won't the meow-normal-define-key suggestion in 1 overwrite the default setting keys for `meow-change` and `meow-line`? Pressing SPC once to go into keypad mode is fine, it's rather that I don't want to leave keypad mode automatically. If the only way to achieve something similar to that is to rebind c and x, then I can of course try that (and move `meow-change` and `meow-line` to another keybind).

**Comment by RKBK** [comment]
Is there a way to trigger shortcuts like 
C-j to add a newline and move point to that line
from keypad mode?

SPC j does C-c C-j which is a different (unbound in my emacs) key combination.

**Comment by DogLooksGood** [comment]
What are you trying to do?

**Comment by RKBK** [comment]
What I'm thinking is that the SPC leader key only goes part-way to avoid holding control and meta to enter commands. As it is now, you can only use the leader key for certain commands. You can't use it to do C-a, C-e, C-j, and other single-key combinations. I still have to use the control key for C-u, for example to do C-u SPC (jump back to the location you just were at). I still need some of those single key combinations, even if many things can be done in the meow normal mode, through other meow-like means. If I still have to press or hold control for some commands, I could just use the control key on my keyboard for all keyboard commands. That's less confusing because it's at least consistent. This is the part that god-mode does so well. Still, I understand that this is the way meow works now, and that's completely fine. Maybe it just a matter of me getting used to the meow way!

**Comment by DogLooksGood** [comment]
The alternative to god-mode is the normal state, not the keypad state. The command layout is not fixed, you can configure according to your preference. Introducing keypad state, is how we solve the endless rebinding for 3rd party packages and most builtin commands. 

Think about every states should has its own usage, using `SPC` to switching between two layers both do the same kind of work is a bad idea. You can bind `meow-universal-argument` to a single key in normal state.

**Comment by RKBK** [comment]
That's a good clarification for me. You need to change your thinking a bit. Thanks for pointing me to meow-universal-argument, and for all your responses.
