### ISSUE TITLE
How do I surround a region with a character?

### ISSUE THREAD

**Issue by RKBK** [meow-edit/meow#357]
One thing I find myself doing often is e.g. quoting a piece of text. For example, going from 
this is a string
to
"this is a string"

Before switching to meow, I had smartparens to give me that ability. Then, I could just select a region and press " to have the region be surrounded by ". I am guessing the idea is that you would use the Beacon state for this.  But, how do I do that in the most efficient way?

**Comment by DogLooksGood** [comment]
You can use all existing packages for parentheses management, paredit, smartparens, and even the Emacs built functions.

For example, a builtin solution. No package required.
```
(define-key global-map (kbd "M-[") 'insert-pair)
(define-key global-map (kbd "M-{") 'insert-pair)
(define-key global-map (kbd "M-\"") 'insert-pair)
```

**Comment by RKBK** [comment]
To clarify, I do have smartparens working. One thing I often do with smartparens is 

1. Mark a region
2. Press " to surround the region with one " at the start and one " at the end

Now, with meow mode, I can select a region, but then I have to switch to edit mode to be able to insert ". But, entering edit by pressing e.g. `i` removes the selection. So, if I then press ", I just get two "" with nothing inbetween. Is there a way to use meow in this situation, or do I have to define additional keys as you suggested above? Alternatively, I can just select a region in edit mode (just as if I didn't use meow at all), but then I can't use all the nice meow selection functionality from normal mode.

**Comment by DogLooksGood** [comment]
Smartparens provedes surrounding commands as well, you can use those without entering the INSERT state. With Meow, it's very common to have a region, in order to prevent disabling selections manually, entering INSERT state will always cancel the selection.

So, the best option here is use those surrounding commands.

**Comment by RKBK** [comment]
Thanks for the explanation!
