### ISSUE TITLE
How to extend regions selected by meow using thing modifiers

### ISSUE THREAD

**Issue by sathishmanohar** [meow-edit/meow#360]
Right now `] p` or `,p` selects one paragraph

* if I want to continue extending the range to the next paragraphs how do i do it.
* Also if I select a round parenthesis (thing) in (some (thing))  how do I extend the range to include the outer round parenthesis also

M-x meow-tutor doesn't seem to cover this

**Comment by DogLooksGood** [comment]
There's no way to do it in meow. 

For case 1, you can use `forward/backward-paragraph`.
For case 2, you can use `repeat`.

**Comment by sathishmanohar** [comment]
This works! Thanks for sharing.
