### ISSUE TITLE
bug: meow-search auto reverse direction when enter grab-selection in backward search

### ISSUE THREAD

**Issue by liuyinz** [meow-edit/meow#373]
Reproduce:

- text example:
```
  "The Program" refers to any copyrightable work licensed under this
License.  Each licensee is addressed as "you".  "Licensees" and
"recipients" may be individuals or organizations.

   To "modify" a work means to copy from or adapt all or part of the work
in a fashion requiring copyright permission, other than the making of an
exact copy.  The resulting work is called a "modified version" of the
earlier work or a work "based on" the earlier work.

  A "covered work" means either the unmodified Program or a work based
on the Program.

  To "propagate" a work means to do anything with it that, without
permission, would make you directly or secondarily liable for
infringement under applicable copyright law, except executing it on a
computer or modifying a private copy.  Propagation includes copying,
distribution (with or without modification), making available to the
public, and in some countries other activities as well.
```
1. `meow-grab ` 2nd paragraph
2. `meow-mark-word` text "or" in 4th paragraph
3. `meow-reverse` change direction, `meow-search` backward
4. when you jump onto last "or" in the grab region, then press `meow-search` again, it will reverse the direction automatically. you need to `meow-reverse` again to continue search backward.
5. if you search into grab region from the first paragraph with direction forward, it won't change direction.
6. I guess maybe in grab region, it may reset the search direction automatically.

**Comment by eshrh** [comment]
reproduced. that's really wacky, I'll investigate...

**Comment by liuyinz** [comment]
And face weired too.
When you search forward into grab-region, `meow-search-highlght` face don't change. But if you enter in backward direction, it suddenly switch to secondary-selection face, and reset direction.

**Comment by DogLooksGood** [comment]
There are two cases when entering BEACON. 
1. The secondary selection is already there, cursor just enters the region.
2. The secondary selection is just created. 

I guess preserving the direction variable doesn't work.

**Comment by liuyinz** [comment]
Sorry, I mistake `region` face and `secondary-selection` face in last comment. What I test is case one.

**Comment by DogLooksGood** [comment]
@eshrh It seems that the L90 in `meow-core.el` is not necessary. We don't have to cancel-selection there.

**Comment by eshrh** [comment]
Did some testing and i don't think it causes any problems.
