### ISSUE TITLE
Select path with leading slash?

### ISSUE THREAD

**Issue by ckeschnat** [meow-edit/meow#380]
Hi,
if I want to select part of a path, e.g. only _/home/me/some/path_ of _/home/me/some/path/file.txt_, I have not found an easy way to do so.

When I'm on the first slash and use `meow-mark-word` followed by some `meow-next-word`, the first one works and _/home_ is selected. After the next `meow-next-word`, only _/me_ is selected.

When I start somewhere on _home_, I can mark everything with a few `meow-next-word`, but the first slash is not included, so I need an additional `meow-reverse` and `meow-left-expand`

I am not sure if this is the intended behaviour.

And as many have said in issues I have seen:
Thank you for this package. I switched from evil a few days ago and am loving it :)

**Comment by DogLooksGood** [comment]
You can create your own "thing" for path. Please check the document of function `meow-thing-register`.

**Comment by ckeschnat** [comment]
Ok, cool. As this is indendet behaviour, I think this can be closed.
