### ISSUE TITLE
Find / Till with a prefix of - is not very intuitive

### ISSUE THREAD

**Issue by sathishmanohar** [meow-edit/meow#382]
Currently F and T aren't bound to anything. In my opinion it'll be more intuitive to bound reverse search with character keys to F and T respectively.

Also if I want to do it manually what are the functions for reverse search. Thanks.

**Comment by eshrh** [comment]
100% agree. There was some discussion earlier about how maybe opposite functionality shouldn't be close together, but I don't think this makes sense when you end up having to press the same key anyway.

They don't exist (reverse searching is only defined as a negative search), but I do it like this:

```emacs-lisp
(defmacro nt--call-negative (form)
  `(let ((current-prefix-arg -1))
     (call-interactively ,form)))

(defun nt-negative-find ()
  (interactive)
  (nt--call-negative 'meow-find))

(defun nt-negative-till ()
  (interactive)
  (nt--call-negative 'meow-till))
```

I doubt this will ever get added.

**Comment by sathishmanohar** [comment]
I politely disagree because using case as a modifier for direction is more intuitive. This navigation pattern is being used throughout VIM. The upside for having the same key is not having to remember two different key combinations for the same thing.

f can find forward and F can find backward.

Also, I'd argue having - sign as a modifier is pretty programmer / math oriented like the below scale

-3 -2 -1 0 1 2 3

Most regular users don't think in these terms and having the same key will make their lives far easier IMO

**Comment by sathishmanohar** [comment]
@eshrh Thanks for the functions. Works perfectly for me. mapped them to F and T 😆
