### ISSUE TITLE
wanted: disable completions popup during run kmacros

### ISSUE THREAD

**Issue by liuyinz** [meow-edit/meow#383]
![Kapture 2022-12-25 at 02 37 25](https://user-images.githubusercontent.com/35212403/209447990-19730b42-7226-4b9e-8405-228d458d3fc0.gif)

Is there any methods to disable the popup completions menu when `kmacro-apply-macro` ? I use lsp-bridge and acm, don't know whether company or corfu problem exists too. And should it be fixed in meow side or completion package side?

**Comment by Linerre** [comment]
I've been using company and corfu for months but never experienced issues like this. So I tend to believe this is a problem from your completion framework. 

In the simplest case, you may want to enable only meow and company, both globally, and see if you can reproduce the issue.

**Comment by liuyinz** [comment]
@Linerre I'm curious, during defining macro, would corfu popup? just like I change the first word jump. I check corfu source code, and it exclude completion when `defining-kbd-macro` is t.  What I want is 
1. when defining macro, it's ok to popup.
2. when apply macro, hide the popup.
does corfu work like this?

**Comment by liuyinz** [comment]
It should be handled in completion package side. details see https://github.com/manateelazycat/lsp-bridge/pull/488
