### ISSUE TITLE
How to disable meow in certain modes

### ISSUE THREAD

**Issue by sathishmanohar** [meow-edit/meow#385]
Meow bindings have some conflicts with packages like magit and git-timemachine. I have to disable meow to interact which those buffers in a reliable way. How do I disable meow in certain buffer modes?

**Comment by DogLooksGood** [comment]
If you don't bind any keys in MOTION state, there should be only 1 conflict, the `SPC` key. The `SPC` will start keypad, and the original command is remapped to `SPC SPC`.  By design, there's at least one meow state enabled all the time.

**Comment by sathishmanohar** [comment]
Got it. In this case how do I manually enable motion mode for a few specific modes.

**Comment by DogLooksGood** [comment]
Check the variable `meow-mode-state-list`, a list of `(major-mode . meow-state)`. 

In general, all text editing buffers should use normal state(includes all kinds of shells), all other modes should use motion state.

**Comment by 45mg** [comment]
What if I want to disable Motion state as well? I usually want `j` and `k` to move by lines, so I have those bindings in Motion state; but there are still some modes where I _don't_ want this.

Would it be correct to define another state with no bindings (or only SPC) for this?

**Comment by DogLooksGood** [comment]
There is no direct support for this. The only way is to define a new meow state, and use that state for the major mode where you want to disable meow completely.
