### ISSUE TITLE
meow-kill calls C-w directly

### ISSUE THREAD

**Issue by slempinen** [meow-edit/meow#389]
### Description

meow-kill seems to call C-w (the built-in kill-region binding) directly. This results in being unable to bind C-w to anything else.

### Steps to reproduce

Add this to your config

```elisp
(meow-normal-define-key '("d" . meow-kill))

(use-package ace-window
  :straight t
  :bind ("C-w" . 'ace-window))
```
Now try to select text and press `d` to kill. It should call `ace-window` instead of killing.

### Version information

* Emacs 28.1 byte compiled from the ubuntu ppa

### Other

This might be intended functionality. If so how should I get around this?

**Comment by DogLooksGood** [comment]
It's controlled by variable `meow--kbd-kill-region`, modify this to another keybinding. 
Meow it's designed to be used with vanilla key bindings, and be friendly for drop-in replacement. 
So if you have another package, which provides you a enhanced kill-region, bound to `C-w` as well, Meow will use it instead.
