### ISSUE TITLE
Magit normal mode keymap not working as expected

### ISSUE THREAD

**Issue by MoritzBoehme** [meow-edit/meow#396]
Hey,
I am fairly new to meow and am currently trying to set it to work nicely with magit.
Before meow, I was using evil and really liked refining what I stage from large hunks by selecting a line and then staging the region. I am now trying to achieve something similar with meow.
My idea was to set the meow state to normal for magit buffers i.e. `(add-to-list 'meow-mode-state-list '(magit-mode . normal))`, so I can select lines as I normally would and then stage them using `SPC s`, which unfortunately does not work. I also tried other magit commands like `magit-discard` via `SPC k`, but cannot seem to get any of the magit changes to work from normal mode.
I assume I'm doing something wrong, but I just cannot figure out what. Does anybody have an idea how to achieve something like what I'm trying to do?
Alternatively, I would be very grateful for a better way to select a region in motion mode to avoid the issue.

**Comment by eshrh** [comment]
Meow doesn't specifically integrate with magit, so you'll have to do it the normal, vanilla emacs way.

Have you tried just using `C-SPC` to start the region? you'll have to use normal `C-n` and `C-p` to include lines. I guess you could add `;` or something to motion make reversing direction more ergo, but you can also just press `C-x C-x`. Once you have your selection you can just press s like usual, assuming you haven't overwritten it with `meow-motion-overwrite-define-key`

**Comment by MoritzBoehme** [comment]
Okay thanks. I don't know the default Emacs bindings all to well, but I think they're ergonomic enough in this case.
I guess it isn't possible to only override motion keys for certain major modes, is it?

**Comment by eshrh** [comment]
Don't worry! I started emacs with doom and for the longest time didn't know anything beyond M-x and C-x C-c...

It's not possible right now. I guess it's possible in theory? 

I can't recommend this, but you could also use something like (untested)
```elisp
(meow-motion-overwrite-define-key
 '("J" . (lambda () (interactive)
           (call-interactively
            (if (eq major-mode 'magit-status-mode)
                #'meow-next-expand
              (key-binding "J"))))))
```

**Comment by MoritzBoehme** [comment]
Thanks, for all the great pointers.
I'll try it out and play around with it a bit.

**Comment by MoritzBoehme** [comment]
I have just tweaked your little snippet to my liking and thought I'd just leave it here if anyone else might like something similar
```elisp
(defun my/meow-define-keys (state mode &rest keybinds)
  "Wrapper around meow-define-keys which only defines a keybind for a specific mode"
  (cl-flet ((modify-keybind (keybind)
              (let ((key (car keybind))
                    (fun (cdr keybind)))
                `(,key  . (lambda () (interactive)
                             (call-interactively
                              (if (eq major-mode ',mode)
                                  #',fun
                                (key-binding ,key))))))))
    (apply 'meow-define-keys state (mapcar #'modify-keybind keybinds))))
```

And I use it like this:
```elisp
(my/meow-define-keys
   'motion
   'magit-status-mode
   '("K" . meow-prev-expand)
   '("J" . meow-next-expand))
```
