### ISSUE TITLE
`meow-normal-state-keymap` overrides `diff-hl-command-map`

### ISSUE THREAD

**Issue by LemonBreezes** [meow-edit/meow#399]
Hello. `diff-hl-command-map` is a repeat map that is triggered by `diff-hl-` commands such as `diff-hl-show-hunk-previous`. However, the Meow's normal state keybindings override `diff-hl-command-map`. How do I change this behavior?

I have a similar issue with  `git-timemachine-mode`, because it is a minor mode rather than a major mode. However, in this scenario, I can use `(add-hook 'git-timemachine-mode-hook
            (lambda ()
              (run-at-time 0.01 nil #'meow-insert-mode +1)))`

**Comment by DogLooksGood** [comment]
Please try the latest commit 1e69067.

**Comment by LemonBreezes** [comment]
Forgot to close this issue but it was in fact fixed by 1e69067.
