### ISSUE TITLE
How do I get rid of the "Frame is too narrow for KEYPAD popup" message?

### ISSUE THREAD

**Issue by SequentialDesign** [meow-edit/meow#409]
How do I get rid of the "Frame is too narrow for KEYPAD popup" message?

I don't want to see it, and I don't want to change my font size. 

TIA. 

PS I don't care about seeing my hotkeys.

**Comment by SequentialDesign** [comment]
The following worked for me. 

```
(defun meow-describe-keymap (keymap)
  (when (and keymap (not defining-kbd-macro) (not meow--keypad-help))
    (let* ((rst))
      (setq rst (reverse rst))
      (let ((msg (meow--describe-keymap-format rst)))
	(let ((message-log-max)
	      (max-mini-window-height 1.0))
	  (save-window-excursion
	    (with-temp-message
		(format "%sKEYPAD: %s%s"
			msg
			(let ((pre (meow--keypad-format-prefix)))
			  (if (string-blank-p pre)
			      ""
			    (propertize pre 'face 'font-lock-comment-face)))
			(propertize (meow--keypad-format-keys nil) 'face 'font-lock-string-face))
	      (sit-for 1000000 t))))))))
```

**Comment by DogLooksGood** [comment]
Additional information, you can use `which-key` as well.

**Comment by DogLooksGood** [comment]
Just enable `which-key`.

**Comment by SequentialDesign** [comment]
oops, you are correct. thanks for the tip. I don't why it didn't work the first time.

**Comment by montchr** [comment]
This is still an issue.

**Comment by DogLooksGood** [comment]
I recommend to use `which-key` as it has more features and well adopted.

**Comment by montchr** [comment]
If that is the case, should Meow's internal implementation be removed/deprecated? Because technically, the issue here still exists until it is either fixed or removed.
