### ISSUE TITLE
Global keybind to "Ctrl-/" gets invoked with pressing "u" key in meow

### ISSUE THREAD

**Issue by sathishmanohar** [meow-edit/meow#410]
I have the following keymap to open vterm by pressing 'ctrl+/` However the same behavior gets invoked when pressing 'u' key for undo.

Basically, Whatever I bind to `Ctrl-/` also somehow gets bonded to `u` key

`(global-set-key (kbd "C-/") 'vterm-toggle)`

I tried when I map other function to the same key binding they get invoked when pressing u

For more context, the global keymap works fine in evil mode. This only happens with meow.

**Comment by DogLooksGood** [comment]
This behavior is controlled by `meow--kbd-undo`.  You can either
1. modify this variable to the keybinding of undo
2. bind undo to `u` in your `meow-setup`

Meow is designed for vanilla keybinding.  It calls the underlying commands by keybinding, so that it works when the original commands are  replaced with alternatives.

**Comment by sathishmanohar** [comment]
I have `'("u" . meow-undo)` in my `meow-setup` I normally use `u` key to undo but when I introduce the above keybind into my emacs config. `u` becomes that keybind automatically overriding `'("u" . meow-undo)`

**Comment by adimit** [comment]
@sathishmanohar I think you didn't quite get @DogLooksGood's response.

When you bind `'("u" . meow-undo)`, that just tells meow to execute `meow-undo` whenever `"u"` is pressed. But what is `meow-undo`?

```
(defun meow-undo ()
  "Cancel current selection then undo."
  (interactive)
  (when (region-active-p)
    (meow--cancel-selection))
  (meow--execute-kbd-macro meow--kbd-undo))
```

So it executes `meow--kbd-undo`. And what's `meow--kbd-undo`? Well, it's `"C-/"`.

So you press "u". And internally, meow tells Emacs, that the user just pressed "C-/". And Emacs goes and does whatever you've set "C-/" to (in your case, open a vterm).

So the solution is to change the value of `meow-undo` to something else. Just don't forget to actually bind the Emacs command `undo` to that something else, or you'll have no `undo`.

**Comment by sathishmanohar** [comment]
I just changed my vterm-toggle keybind to `C-c C-/` Now `u` doesn't toggle vterm.
