### ISSUE TITLE
Beacon fake cursors on symbols instead of words?

### ISSUE THREAD

**Issue by MichaelXavier** [meow-edit/meow#412]
I've run across a use case that I thought would be good for beacon mode but I can't get it to work. Here's the before and after:
```
(oneTwo threeFour fiveSix)
(A.oneTwo A.threeFour A.fiveSix)
```
I first start in the parens and do `,r` to select within the parens, then `G` to start meow mode. However, if I do `meow-back-symbol` or `meow-forward-symbol`, I would expect fake cursors to be placed at the `>` in `(>oneTwo >threeFour >fiveSix)`, or one at the beginning of each symbol, but instead they always appear wordwise: `(one>Two >three>Four >five>Six)`. I looked through the tutorial but noticed that all of the examples of auto-placement of fake cursors seem to go by word. If meow can only place them by word and not other objects like symbols, it seems difficult to use the feature, because in code you're more often dealing with symbols rather than words.

Am I missing something or perhaps is my setup misbehaving?

**Edit**

I remembered that in the specific code mode I was in I had set up a hook to add `subword-mode` which I thought might be messing things up.  Turning that off, removing the hook and reloading the file makes it so the above sample works, but for some reason if there are underscores in the symbols, even though meow usually seems to understand that underscores are part of symbols, beacon mode splits at the underscore:
```
(oneTwo_a threeFour_a fiveSix_a)
```
When you try to use `B` or `E` to put cursors on the start or end of each symbol, it does `(>oneTwo_>a >threeFour_>a >fiveSix_>a)`, whereas I'd expect it to be `(>oneTwo_a >threeFour_a >fiveSix_a)`.

**Comment by DogLooksGood** [comment]
Yep, I think it's a problem.  Meow's symbol selection is only available for same symbols in beacon state, there's no beginning or end of each symbols.  I think we could have a fix.

**Comment by Haxxflaxx** [comment]
Is this hard to add?
I've been digging around a bit in the code to see how the cursors are created, but I can't seem to find how this is triggered by a motion.

**Comment by DogLooksGood** [comment]
@Haxxflaxx 

It's not hard, but a breaking change. The steps are

1. Add a selection type `symbol`, current symbol motions use type `word`.
2. Let symbol motions create `symbol` type selection.
3. Update `meow--beacon-update-overlays` to handle the `symbol` type selection.

The breaking change is now using a word motion after symbol motion will cancel the current selection, vice versa. But I don't see it a big problem.  Of course, PR for this is welcomed!

**Comment by DogLooksGood** [comment]
#650
