### ISSUE TITLE
用use-package的时候，meow-cheatsheet-layou设置不了

### ISSUE THREAD

**Issue by pipiTan** [meow-edit/meow#415]
meow-setup里有(set meow-cheatsheet-layou meow-cheatsheet-layout-qwerty)，use-package会直接出错，说找不到这个变量。
<img width="515" alt="图片" src="https://user-images.githubusercontent.com/18749923/225375693-5f12c7d8-7c7e-4c43-9957-4621dc4c41f5.png">
这样也没用。

**Comment by DogLooksGood** [comment]
你需要了解下 use-package 的机制，`:init` 是在 package 加载之前执行的，所以变量是无效的。`:config` 是在加载之后执行的，所以在 `:config` 里面包提供的变量才是有效的。

```
(use-package xxx
   :init yyy
   :config zzz)
```

近似于

```
(require 'xxx) 或 (autoload 'xxx)
yyy
(with-eval-after-load "xxx"
   zzz)
```

**Comment by pipiTan** [comment]
狗哥，请问正确的使用方法是什么？
我是发现在meow-setup()这个函数里有上面setq的个东西时，use-package都是不能生效的。而且注释setq后，要在:init里用meow-globa-mode和meow-setup才能正常使用。

**Comment by DogLooksGood** [comment]
可以把 meow-setup 放在 :config 里面。

**Comment by pipiTan** [comment]
感谢狗哥。我只用require就好了。
不过我发现(meow-goto-line)好像有问题，执行它不会跳转到相应的line，而只会选中当前行，是bug吗？

**Comment by DogLooksGood** [comment]
meow-goto-line 会调用当前的 `meow-goto-line-function`, 默认的情况下就是 `goto-line`. 效果是跳到一行并选中那一行。

**Comment by pipiTan** [comment]
> meow-goto-line 会调用当前的 `meow-goto-line-function`, 默认的情况下就是 `goto-line`. 效果是跳到一行并选中那一行。

可是它并不会跳到相应的某一行。
![Mar-18-2023 23-28-38](https://user-images.githubusercontent.com/18749923/226115240-6c46864a-9a14-4f24-8d50-eb7350e0c723.gif)

**Comment by DogLooksGood** [comment]
默认的时候是会找  `M-g` 上面的命令，因为默认的是 `goto-line`. 

所以你可以指定 `(setq meow-goto-line-function 'goto-line)`.

**Comment by pipiTan** [comment]
> 你需要了解下 use-package 的机制，`:init` 是在 package 加载之前执行的，所以变量是无效的。`:config` 是在加载之后执行的，所以在 `:config` 里面包提供的变量才是有效的。
> 
> ```
> (use-package xxx
>    :init yyy
>    :config zzz)
> ```
> 
> 近似于
> 
> ```
> (require 'xxx) 或 (autoload 'xxx)
> yyy
> (with-eval-after-load "xxx"
>    zzz)
> ```

我找到出问题的地方了，要在use-package里加上:demand t才能正确加截
