### ISSUE TITLE
Automatic selections disappear

### ISSUE THREAD

**Issue by MichaelXavier** [meow-edit/meow#419]
I may be totally misunderstanding how this is supposed to work but I've noticed that a lot of mow operations like `meow-change`  and `meow-yank` tend to leave a selection for the unit of text that's been acted upon. So for meow-yank, if I paste in some text, it will be selected. Often I want to do a find/replace within the thing I just pasted to modify it for the context I've pasted it into. However, if I try to `M-x` or even if I bind something like `meow-query-replace-regexp`, the instant the focus goes to the minibuffer to prompt me, I lose my selection in the text and the command no longer acts on that region. Is that supposed to happen?

**Comment by DogLooksGood** [comment]
The selections are regions, they suppose to be disabled when text is modified.  But, the following sounds weird to me
> if I try to M-x or even if I bind something like meow-query-replace-regexp, the instant the focus goes to the minibuffer to prompt me, I lose my selection in the text and the command no longer acts on that region.
The selection will not be deactivated just because the cursor goes to another buffer(minibuffer).  Otherwise, there's no way to do query replace.

**Comment by MichaelXavier** [comment]
Looking more closely, it seems like most operations that leave a region that I can think of work as expected by staying selected when you try to run `query-replace-regexp` or something. It seems like the only case where it deselects is after `meow-yank`. It seems like the region itself while visually still selected isn't actually active and any operations you perform act on where the cursor is. Let's say in the following example that `|` represent the edges of the region after `meow-yank`ing some code and `>` is the cursor. After I yank:

```
blah
|foo
bar|
>baz
```
If I hit `s`, I would expect the region I just yanked in to be deleted like this:
```
blah
>baz
```
Instead, the region is ignored and the s acts on the word that my cursor is currently on, so this is the result
```
blah
foo
bar
>
```

**Comment by MichaelXavier** [comment]
I think what may be going on here is according to [this page on yanking](https://www.gnu.org/software/emacs/manual/html_node/emacs/Yanking.html) emacs sets the region to the beginning of the yanked text and then I guess has the cursor outside of that region which I think causes that region to deselect right away. I don't really understand why they do this. But if I do `C-x C-x` or `exchange-point-and-mark` it actually selects the just-yanked text so that I can further manipulate it. I could just get used to hitting `C-x C-x` after yanking if I want to edit the yank. Let me know if there's maybe a better way to do it.

**Comment by DogLooksGood** [comment]
The inserted texts shouldn't be selected or visually selected.  But yes, you can select the inserted texts by hit `C-x C-x`.
