### ISSUE TITLE
How to programmatically map keys?

### ISSUE THREAD

**Issue by rickalex21** [meow-edit/meow#425]
Hello, I was able to get the variable `func` to work but can't figure out how to do a lambda.

```lisp
(let ((key "zo")
     (func 'find-file)
     (func2 '((lambda ()(message "hello" )))))
  (meow-leader-define-key `,(cons key func)))
```

Thanks

**Comment by DogLooksGood** [comment]
Could you tell more about your purpose?

**Comment by rickalex21** [comment]
I'm passing keys to a function that does the mapping. For lambdas I do a third argument which
in turn calls `which-key-add-key-based-replacements` to have a meaningful name (e.g., "Archive").

```lisp
(my/map-keys `(
 ("C-c o A" ,#'(lambda ()(interactive)(when (yes-or-no-p "Archive?") (org-archive-subtree))) "Archive")
 ("C-c o d" ,#'org-cut-subtree))
```
I am using `define-key` in the function which automatically would become available as leader
as long as I use `C-c` but I was wondering if there was a way to do what I mentioned above?

**Comment by DogLooksGood** [comment]
Then for every `("<KEY>" <COMMAND> [NAME])`:
First you use `meow-leader-define-key` to define the key binding, then you put something into `which-key-add-key-based-replacements`.  It seems to be straightforward?

**Comment by rickalex21** [comment]
@DogLooksGood  I forgot to add interactive 🫤. Programmatically mapping my keys actually came in useful now that I have to change `define-key` to `keymap-set`. I don't have to regex query replace in all my files where I have `define-key`, I only change my function that maps keys.

Why does `?closure` still come up in which key?

```lisp
(let ((key "z o")
     (func 'find-file)
     (func2 '(lambda ()(interactive)(message "hello" ))))
  (meow-leader-define-key (cons key func2))
  (which-key-add-key-based-replacements (concat "SPC " key) "meow-stuff"))
```

**Comment by rickalex21** [comment]
This works though, I guess don't use `meow-leader-define-key` at all because I can define all keys
that I need with `C-c` then do which key? I understand that keypad uses some keys so I have to
pay attention to which keys I decide to use because meow uses `x` for `M-x` in keypad.

```lisp
(let ((key "C-c z o")
     (func 'find-file)
     (func2 '(lambda ()(interactive)(message "hello" ))))
  ;;(meow-leader-define-key (cons key func2))
  (keymap-set  global-map key func)
  (which-key-add-key-based-replacements key "meow-stuff"))
```
