### ISSUE TITLE
Disable keypad

### ISSUE THREAD

**Issue by schrenker** [meow-edit/meow#426]
Hello,

Is there a way of disabling keypad functionality completely, other than binding SPC to ignore function? I really like modal editing part of meow, but with keyboard I have, I don't need and want keypad functionality enabled.

Thanks,
Kind Regards

**Comment by DogLooksGood** [comment]
What do you mean by "disabling completely", if SPC is not bound to `meow-keypad`, there won't be a way to enter this mode. Thus it's disabled completely.

**Comment by schrenker** [comment]
Yeah, I was thinking about something more absolute, like setting variable to nil. But that also works, I was just wondering if this is the 'official' way I guess. Thanks for the answer.
