### ISSUE TITLE
How to use C-u prefix?

### ISSUE THREAD

**Issue by morgandavidson** [meow-edit/meow#428]
For example, in an `org-table`, `C-c =` adds `$1=` to `#+TBLFM:` where `C-u C-c =` adds`@1$1=`.

With meow I can do `C-c =` with `SPC c =`. How can I do `C-u C-c =`?

**Comment by DogLooksGood** [comment]
Prepend `universal-argument`, use `C-u` or `SPC u`.

**Comment by morgandavidson** [comment]
`C-u SPC C =` adds `@1$1=` indeed, but `SPC u` writes "u "in the buffer.

**Comment by DogLooksGood** [comment]
Oh, sorry. You just bind `SPC u` (or whatever key) to `meow-universal-argument`.
```
(meow-leader-define-key '("u" . meow-universal-argument))
```

**Comment by morgandavidson** [comment]
Thank you, it now works, but `SPC` has to be hit twice : `SPC u SPC c =`
```
  (use-package meow
    :init
    (meow-global-mode 1)
    (define-key meow-motion-state-keymap (kbd "<escape>") nil)
    :bind
    ("z" . meow-insert)
    ("u" . meow-universal-argument)
    )
```

**Comment by morgandavidson** [comment]
Actually, my config wasn't working properly because I was unable to type the letter "u" when in insert mode. Here is the correct config:

```
  (use-package meow
    :init
    (meow-global-mode 1)
    (meow-leader-define-key '("u" . meow-universal-argument))
    )
```
Thanks again.

**Comment by DogLooksGood** [comment]
I think they should be put into `:config` instead of `:init`. I don't use `use-package`, but it seems that in `use-package`, `:init` will be evaluated before loading the package.
