### ISSUE TITLE
How to use keypad without using motion ?

### ISSUE THREAD

**Issue by morgandavidson** [meow-edit/meow#429]
Thank you for this great package! Meow has lots of functionalities, I started using for its keypad-mode. 

My usage is not to have meow-mode enabled by default, but only launching meow-keypad when I need to type a complex keybinding.

Each time I do that, I'm then sent to MOTION and have to type `i` to exit .

Would it be possible to be automatically out of meow after having typed the keybinding through meow-keypad (i.e. once the command is executed)?

Here is my config : 
```
  (use-package meow
    :init
    (define-key input-decode-map [?\C-m] [C-m])
    :config
    (global-set-key (kbd "<C-m>") 'meow-keypad)
    (meow-leader-define-key '("u" . meow-universal-argument))
  )
```

**Comment by morgandavidson** [comment]
I read the thread about One-shot god-mode, but it didn't help me find out how to avoid being sent to motion-mode after using keypad.

**Comment by DogLooksGood** [comment]
Yep, if you are only looking for a one-shot keypad, you should use this one-shot god-mode.

**Comment by morgandavidson** [comment]
I just tried god-mode. I found it less useful than meow, since command names aren't shown in the minibuffer.

Plus, when you do `god-local-mode`, after typing your keybinding you're still inside `god-local-mode`. You have to toggle `god-local-mode` again to exit. Which is the same as exiting MOTION. 

So I see no added value in using god-mode for my use-case.

**Comment by eshrh** [comment]
You could also try hooking `meow-motion-mode-hook` to disable meow every time it enters the state, or adding advice after the function `meow--exit-keypad-state`.
