### ISSUE TITLE
Mode-specific thing table?

### ISSUE THREAD

**Issue by MichaelXavier** [meow-edit/meow#438]
Is it possible to append to meow's table of things for specific modes? For example, there may be some things that are particular to markdown-mode or org-mode. I wouldn't want to define them globally because they'll clutter the menu when I'm trying to select a thing. They may even be defined differently in different modes. Furthermore, putting everything in the global thing map means the character you use to indicate a thing will more likely already be taken.

**Comment by DogLooksGood** [comment]
Firstly, use `make-variable-buffer-local` to make variable `meow-char-thing-table` buffer-local.
Then use major mode hooks and `setq-local` to set values separately.

**Comment by MichaelXavier** [comment]
Is the idea then to all of the things globally with `meow-thing-register` and then reference them selectively by making `meow-char-thing-table` buffer-local?

**Comment by DogLooksGood** [comment]
`meow-thing-register` will registry a thing with a **NAME** to meow--thing-registry. And `meow-char-thing-table` is the mapping from key char to **NAME**. So you don't have to use `meow-thing-register` until you want to create your own thing.

**Comment by MichaelXavier** [comment]
Thanks! I'll go ahead and close the ticket.
