### ISSUE TITLE
How can I set default initial state to insert?

### ISSUE THREAD

**Issue by SequentialDesign** [meow-edit/meow#441]
Is there a way to make the insert state the default state?

**Comment by SequentialDesign** [comment]
Never mind. Advising `meow--enable` with
```
(meow-normal-mode)
(meow-insert-mode)
```
works.

**Comment by eshrh** [comment]
this should be done on a per-mode basis, by modifying `meow-mode-state-list`. Of course you can also target `fundamental-mode`.
