### ISSUE TITLE
Can't get `meow-open-below` to work on `A`

### ISSUE THREAD

**Issue by VOID404** [meow-edit/meow#442]
`A` seems to be bound correctly, and yet it does not behave like it is... It seems to put the cursor at the end of the line, input "A" and put me in input mode. It works in `meow-tutor`, but breaks in the same way if I enable `prog-mode` (even if I go back to fundamental afterwards). `meow-open-above` works as expected.

[Here](https://github.com/VOID404/emacs-config/)'s my current config, if you'd like to take a look.

Expected result:
<img width="580" alt="image" src="https://user-images.githubusercontent.com/9433601/234607746-4435014d-2082-42ef-9154-98e87c67880b.png">
Actual result:
(as you can see in `view-lossage`, the correct command seems to be called)
<img width="1188" alt="Screenshot 2023-04-26 at 16 27 37" src="https://user-images.githubusercontent.com/9433601/234607543-8c8bc957-cc65-4985-9b3d-dd0f028f4420.png">

**Comment by VOID404** [comment]
`(autopair-newline)` is bound to `RET`.
`meow-open-below` works correctly if I call it from `M-x`, it doesn't if I call it with `A`.

Aaaannnddd that was in fact the problem 🤦. 
Is there a list of "what gets called on `x`"?
How is it possible, that when called with an `A` key it breaks with autopair, but with `M-x meow-open-below` it works regardless?

**Comment by Linerre** [comment]
In that case, what do you get if you try `C-h k A`? Sounds like your “A” is rebound to sth that behaves like Vim’s A (insert at end of line)

Noel Errenil
________________________________

**Comment by VOID404** [comment]
```
A runs the command meow-open-below (found in
meow-normal-state-keymap), which is an interactive native-compiled
Lisp function in ‘meow-command.el’.

It is bound to A.

(meow-open-below)

Open a newline below and switch to INSERT state.

[back]
```

`view-lossage` in my first message also says that it calls `meow-open-below`

**Comment by VOID404** [comment]
I solved it by switching to `electric-pair-mode`, but I'd still love to understand why it behaves differently called with `A`, and differently called with `M-x meow-open-below`...

**Comment by Linerre** [comment]
Ok. Then when you press A, Emacs calls `meow-open-below` to insert a new line below the current one.

I guess it moves the cursor first to the line end, and then calls `RET`. However, your `RET` behavior might have been modified by that auto pair stuff. Could you try to disable that auto-pair package and see if meow would insert a new line below correctly?

Noel Errenil
________________________________
