### ISSUE TITLE
Does Keypad not work in Motion buffers? 

### ISSUE THREAD

**Issue by SequentialDesign** [meow-edit/meow#444]
Keypad works great for me save in Motion buffers. Is that normal?

In motion buffers, `space` inserts itself and does not act as a way to get non-Control keys. It works fine in other non-Motion buffers. 

Even when I switch to Insert, Keypad doesn't work properly. `space` doesn't work as it should/does in other buffers. Very weird.

**Comment by DogLooksGood** [comment]
Keypad is a standalone state in Meow. To enter this state, the default binding  is `SPC`. Check the keybinding by `C-h k SPC` in a buffer where it doesn't work.

**Comment by SequentialDesign** [comment]
Yes, the Keypad state is broken in motion buffers. It doesn't work as it should. It activates, but the space leader (for literal binds) is borked. Not a big deal at all (Meow is overpowered), but still a problem.

**Comment by SequentialDesign** [comment]
Okay, I see now. You have to hit `space` to get a literal character. That is fine.
