### ISSUE TITLE
Normal mode and motion mode on at the same time after entering a motion mode buffer

### ISSUE THREAD

**Issue by slempinen** [meow-edit/meow#445]
Hello!

Sometimes when I enter a buffer that defaults to motion mode (for example a dired or a ibuffer buffer) the meow modeline indicator appears twice on the modeline. It seems that normal mode and motion mode are both on at the same time. See the pictures below.

![meow-bug-1](https://user-images.githubusercontent.com/95316322/235311797-5949f08a-f8f9-4f1d-ade2-e8fd3fc95659.png)

![meow-bug-2](https://user-images.githubusercontent.com/95316322/235311799-b94d31c1-8022-4c1e-9b31-f420e21bcee6.png)

Note the `[M]` and `[N]` indicators. When this happens emacs seems to interpret my input as if it were in normal mode. Needless to say this is a bit confusing. The problem goes away when I left click on the `[N]` indicator and click on "Turn off minor mode".

The interesting thing is that it only happens sometimes and not always. I have not figured out a reoccurring pattern that could explain why this happens. Is this a bug you have encountered earlier?

I run emacs 28.1 with native compilation from the [ubuntu ppa](https://launchpad.net/~kelleyk/+archive/ubuntu/emacs) on ubuntu linux. Let me know if I can give you more information. My meow setup has no custom configurations apart from keybindings so I have not messed with variables that affect mode selecting.

**Comment by DogLooksGood** [comment]
Any tweaking for mode switches in your configuration?

**Comment by slempinen** [comment]
No tweaking on modes. Only tweaks that should affect meow are my keybindings.

**Comment by DogLooksGood** [comment]
The behavior is controlled by variable `meow-mode-state-list`. Do you have either of the them enabled with hooks?

**Comment by eshrh** [comment]
Odd. Would you link to your entire config?

**Comment by slempinen** [comment]
Sorry for not replying. I have been waiting for this bug to appear again but for the past couple of weeks it has not come up. I did some major changes to my config recently like going from company to corfu, from lsp mode to eglot etc. so there is a chance that I fixed it by accident. I'll make a new issue if it comes up again! 

Thank you guys for maintaining this awesome package :)
