### ISSUE TITLE
Spacemacs integration

### ISSUE THREAD

**Issue by sdmoralesma** [meow-edit/meow#447]
Hi, just wondering if you have considered providing a module for Spacemacs.

**Comment by DogLooksGood** [comment]
Hey, I don't use Spacemacs. But I guess there's nothing special.
Disable evil and enable meow is all you need?

**Comment by sdmoralesma** [comment]
I know that the doom-meow integration enables some extras like +leaderkey +{keyboard-type} and not sure if just enabling it will be enough for these cases, or even if it would have some conflicts. Also, I've seen many people interested in Modal Editing in general and Spacemacs has a potentially large audience, so, at least some documentation on how to make it work could be very useful for all.

**Comment by DogLooksGood** [comment]
Well, there's no extra features introduced in the module. doom-meow tries to separate each parts, make them optional. If there's module for spacemacs, it will be as simple as what you do without spacemacs or doom. If you want to disable a state, just unbind the corresponding keybinding. For example, if you don't like KEYPAD, then just unbind `SPC` in NORMAL and MOTION.

![image](https://user-images.githubusercontent.com/11796018/235539435-f079f35b-12f0-49f4-b6ee-2e2cc3ceb6b5.png)

**Comment by sdmoralesma** [comment]
Ok, thank you for the info! Below is the configuration for Spacemacs in case someone else needs it:

In the `.spacemacs` file add `meow`. It will be downloaded from Melpa:
```
dotspacemacs-additional-packages '(meow)
```

Define a `meow-setup` function and call it from the `dotspacemacs/user-config` function as:
```
  (use-package meow
    :config
    (meow-setup)
    (meow-global-mode 1))
```
Reload the configuration and check that it works by showing the cheatsheet `SPC ?`.
