### ISSUE TITLE
`quit-window` or `delete-window`

### ISSUE THREAD

**Issue by bzy-debug** [meow-edit/meow#450]
Hello, thanks for your great package! It really helps a lot!
However, currently I'm coming across some inconsistency with this package.
Currently `meow-quit` calls `delete-window` by default, however some frequently used mode (help-mode, dired-mode) uses `quit-window` by default.
For me, in most cases, `quit-window` is more useful than `delete-window` since it only buries buffer if the window has other buffer opening so that it won't disturb the work flow. 
For example, with two window opened, `C-h` in one window will open help-buffer in the other one. `C-x o` to go the other window. At this circumstance, `delete-window` deletes the window while `quit-window` only buries the help buffer and keeps the display configuration unchanged.

I'd like to know why you choose `delete-window` instead of `quit-window` ? And is it a good idea to replace `delete-window` with `quit-window`?

Thanks again for your great package! :)

**Comment by DogLooksGood** [comment]
You are right, `quit-window` works better in this case. I'll update `meow-quit` to use that.

Thanks for sharing the details!

**Comment by bzy-debug** [comment]
Great! Thank you!
