### ISSUE TITLE
Keypad provides command from global keymap instead of major-mode keymap

### ISSUE THREAD

**Issue by fast-90** [meow-edit/meow#466]
I have the following in my config:

```elisp
(keymap-global-set "C-c o" #'consult-outline)
(keymap-set org-mode-map "C-c o" #'consult-org-heading)
```

When I press `C-c o` in an org-mode buffer, I get `consult-org-heading` and in all other types of buffers I get `consult-outline`, which is the behaviour I want. However, when I press `SPC o` I get `consult-outline` even in org-mode buffers.

Is this a bug in meow? Or is the way I bind my keybindings incorrect in any way?

**Comment by DogLooksGood** [comment]
Try add `(setq meow-keypad-leader-dispatch "C-c")`.

**Comment by fast-90** [comment]
> Try add `(setq meow-keypad-leader-dispatch "C-c")`.

Thanks, this worked for this particular problem but breaks other things. Now my bindings under the leader key (e.g. `C-c ?` to show the meow cheatsheet) don't work anymore.

After some further digging, I finally understand why: `mode-specific-map` is actually [not "mode-specific"](https://www.gnu.org/software/emacs/manual/html_node/elisp/Prefix-Keys.html), but a global map.

I don't think this is a meow issue as it was designed to use `mode-specific-map`, therefore I'm closing the issue.

For those interested, I found another way around my problem with the following function:

```elisp
  (defun my/consult-outline ()
    "Use consult-org-heading if in org-mode, otherwise use consult-outline."
    (interactive)
    (if (equal major-mode 'org-mode)
        (consult-org-heading)
      (consult-outline)))
```

**Comment by DogLooksGood** [comment]
Hey, actually, you should avoid using keybindings like `C-c ?`. According to Emacs key binding convention, user should use `C-c <letter>`.

**Comment by fast-90** [comment]
> Hey, actually, you should avoid using keybindings like `C-c ?`. According to Emacs key binding convention, user should use `C-c <letter>`.
> 
> https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html

Apologies, that was a mistake in my previous post. What I meant is that `SPC ?` for the cheatsheet (which I bind via the suggested config in the README) did not work anymore after setting `meow-keypad-leader-dispatch`. Instead, `SPC ?` now invokes the command under `C-c ?` which is not what I want.

I will update the previous post for clarity for future readers.
