### ISSUE TITLE
Some letters insert character in vterm while in normal mode

### ISSUE THREAD

**Issue by fast-90** [meow-edit/meow#467]
In my vterm buffer, when I type the letter `l` it just inserts the character "l" instead of going to the right. Same happens with other letters like `j`, `k`, `d`, but not all (e.g. `h`, `x` and `a`).

Is this a bug? Or is something wrong with my config? In the case of the latter, how would I best explorer where the error in my config is?

**Comment by DogLooksGood** [comment]
Is that `NORMAL` state is used?

**Comment by fast-90** [comment]
> Is that `NORMAL` state is used?

Yes, when I look at the `meow--current-state` it says "normal", as does my mode-line. When I type `x` it works as expected, i.e. it selects the whole line.

**Comment by DogLooksGood** [comment]
I don't use vterm myself, but I found this:
https://github.com/accelbread/meow-vterm

**Comment by fast-90** [comment]
Thanks for the link! I can confirm that the linked package solved my issue! Maybe it's worth a mention in the README? In any case I will close this issue.

**Comment by DogLooksGood** [comment]
If it works, those hacks should be introduced into this repo.

**Comment by chuxubank** [comment]
This https://github.com/accelbread/meow-vterm works well for `vterm`, but I'm curious about why `meow-mode-state-list` set the value of `vterm` and `term` mode to `normal` state?
Should this hack be included into the main repo?

**Comment by DogLooksGood** [comment]
Well, by design, every buffers with text editing, should start with normal mode. And insert mode shouldn't be used as default mode for consistency, as leader key is not available in insert mode.

**Comment by ahan98** [comment]
I still have this issue even with `meow-vterm` installed. Navigation keys `hjkl` work, but none of the meow editing commands like `meow-kill` work. I've tried with all combinations of `vterm-copy-mode` and `read-only-mode` enabled/disabled. Am I missing something? I know that vterm reads literal key inputs so to get certain keybindings to work, e.g., `C-w`, you might have to do something like `(vterm-send-key "\C-w")`, but it seems ridiculous that you'd have to resort to hardcoding every keybinding that you want.
