### ISSUE TITLE
Normal mode on top of motion mode buffers loaded at startup

### ISSUE THREAD

**Issue by schrenker** [meow-edit/meow#469]
Hello,

My meow config can be found here: https://github.com/schrenker/emacs.d/blob/master/init.el#L1520

Upon startup, any buffers that are loaded in, by another package, either package installation via elpaca, or dired, and that mode has been specified to start in motion mode, normal mode will be appended on top of it, effectively overriding motion mode. Below are the screenshots of variables from one of my dired/dirvish buffers after restart:

![image](https://github.com/meow-edit/meow/assets/42305809/89860637-780a-4c7d-9c20-322a20e2a2af)

As you can see, meow-motion-mode is set to t, and meow-normal-mode is set to 1. I am unsure what is causing this, but nowhere in my config I am setting this. This happens to every motion mode buffer, if it is loaded on startup. After startup, entering these buffers work fine.

I saw that someone already reported this issue here, https://github.com/meow-edit/meow/issues/445 but it seems that person made a lot of changes to their config, so the reason for the issue is not known.

If there is more information needed, please let me know.

**Comment by DogLooksGood** [comment]
Hey, how your buffers opened? I guess the order matters.

**Comment by schrenker** [comment]
Hello,

I am using a package called perject https://github.com/overideal/perject . It's using desktop.el underneath to save and load buffers. 

Should the order matter though? If a major mode has a meow mode specified for it in meow-mode-state-list, I would assume that it would be assigned to it on startup of either the buffer, or meow. I also tried moving meow use-package block to the beginning of init.el file, with no successes as well. 

Note that this issue also happens for elpaca ui buffers, which are not loaded by perject package, but can appear, if for example new use-package block was added in previous session, but that package wasn't installed yet (elpaca will install it on startup).

**Comment by DogLooksGood** [comment]
I'll try to reproduce with perject.

**Comment by schrenker** [comment]
I was looking for anything that could set the meow-normal-mode to 1. There is a function in meow-util.el:
```
(defun meow--init-buffers ()
  "Enable meow in existing buffers."
  (dolist (buf (buffer-list))
    (unless (minibufferp buf)
      (with-current-buffer buf
        (setq-local meow-normal-mode 1)))))
```

And then meow--global-enable in meow-core calls it:

```
(defun meow--global-enable ()
  "Enable meow globally."
  (setq-default meow-normal-mode t)
  (meow--init-buffers)
...
  (add-hook 'desktop-after-read-hook 'meow--init-buffers)
...
```

Could this be the issue? My elisp-fu is still weak, and I might be wrong, but I am trying to find the reason for this :D

**Comment by DogLooksGood** [comment]
Ah, you remind me. I think we should add a check in `meow--init-buffers`. Only set meow-normal-mode when none of these modes enabled.

**Comment by schrenker** [comment]
I think commit https://github.com/meow-edit/meow/commit/850fa13dffb8075f9e8eb3bdca576422a448088a fixes this, as the person reporting had the same problem as I did.

**Comment by schrenker** [comment]
I think commit https://github.com/meow-edit/meow/commit/850fa13dffb8075f9e8eb3bdca576422a448088a fixes this, as the person reporting had the same problem as I did. I will close, and reopen in case this happens again.
