### ISSUE TITLE
Highlighting problem when using emacs client

### ISSUE THREAD

**Issue by zenitsh** [meow-edit/meow#470]
在使用emacs client时，序号的高亮出现问题，导致序号可能与原来的文本混淆：
![image](https://github.com/meow-edit/meow/assets/71211256/ea74e7a2-6e43-41d2-96c2-f5cbb4f508c4)
在手动加载主题后，可以正常高亮序号：
![image](https://github.com/meow-edit/meow/assets/71211256/27c55555-cae5-426e-8e0e-5fa867407c62)
Disable主题之后，没有恢复之前的默认样式：
![image](https://github.com/meow-edit/meow/assets/71211256/b1a7652d-a8fd-4338-aa6b-45b96a602adb)
这是默认的样式的高亮效果：
![image](https://github.com/meow-edit/meow/assets/71211256/61325c3c-4d9f-4ca6-8fb6-57e84f90bf39)

启动emacs client的命令：
```
emacs --daemon
emacsclient --create-frame
```
meow配置：
```
(use-package meow
  :ensure t
  :init
  (meow-global-mode 1)
  :config
  (meow-setup))
```
其中meow-setup使用的是默认的qwerty键位的配置，没有改动。

**Comment by udayvir-singh** [comment]
@zenitsh I fixed it by adding the following code in my config:

```elisp
(set-face-attribute 'meow-position-highlight-number-1 nil
                    :foreground "#16111d"
                    :background "#95c6cc")
```

**Comment by zenitsh** [comment]
@udayvir-singh
Thank you for your advise.

It seems that Emacs server doesn't create a frame when launching, so the “meow--prepare-face” function (in "meow-face.el") could not get the correct color of the frame. I've found a hook that runs when a client frame is created. And I make meow to be initialized after the real frame being created.

Here is my code:
```
(add-hook 'server-after-make-frame-hook (lambda () (meow-global-mode 1)))
```

**Comment by zenitsh** [comment]
To avoid initializing meow twice:
```
(add-hook 'server-after-make-frame-hook (lambda () (meow--prepare-face)))
```

**Comment by udayvir-singh** [comment]
@zenitsh You don't have to wrap `meow--prepare-face` in a lambda function, it can be directly passed to the hook:
```elisp
(add-hook 'server-after-make-frame-hook #'meow--prepare-face)
```
