### ISSUE TITLE
Meow support for emacs default keybinding

### ISSUE THREAD

**Issue by traxyax** [meow-edit/meow#471]
I really like meow and Emacs default key-binds. I would like to know if it is possible to combine the two. For example, using `C-n` `next-line` will use `meow-next` and provide the visual hints.

**Comment by DogLooksGood** [comment]
Unfortunately, it can't. Meow calls the underlying command by key binds, so it's quite complex to achieve what you described.

**Comment by traxyax** [comment]
I understand. Thanks.
