### ISSUE TITLE
Please tag new release

### ISSUE THREAD

**Issue by davidarnold** [meow-edit/meow#478]
I am using Meow from [NonGNU ELPA](https://elpa.nongnu.org/nongnu/meow.html) and would like to use newer features like the `meow-keypad-self-insert-undefined` variable.

It seems like a lot has been added since version 1.4.2 https://github.com/meow-edit/meow/compare/v1.4.2...master

Thank you 😸

**Comment by DogLooksGood** [comment]
Just updated the [changelog](https://github.com/meow-edit/meow/blob/master/CHANGELOG.md#143-2023-07-11), there aren't many new features actually, they are mostly bugfixes.

New tag `v1.4.3` pushed.

**Comment by davidarnold** [comment]
Thank you!
