### ISSUE TITLE
Add advice `meow--prepare-face` to `enable-theme` instead of `load-theme`

### ISSUE THREAD

**Issue by HardGraphite** [meow-edit/meow#487]
At present, the advice function `meow--prepare-face` is added to the function `load-theme` ( [meow-core.el:193](https://github.com/meow-edit/meow/blob/master/meow-core.el#L193), [meow-core.el:213](https://github.com/meow-edit/meow/blob/master/meow-core.el#L213) ). `meow--prepare-face` sets colors by calling `set-face-attribute`, which will be overridden if a new theme is enabled. This is fine when the new theme is enabled with `load-theme` because the advice will then re-prepare the colors. However, the colors will go wrong if the new theme is enabled with `enable-theme`.

I suggest adding advice `meow--prepare-face` to `enable-theme` instead of `load-theme`. First, this fixes the color problem after `enable-theme`. Second, the modification does not change the current behavior, because `enable-theme` is called at the end of `load-theme`, and calling `load-theme` also triggers advice on `enable-theme`.

**Comment by DogLooksGood** [comment]
Hey, thanks! 
Would you like to make a PR for this?
