### ISSUE TITLE
How to trigger keypad description with "?" key?

### ISSUE THREAD

**Issue by HardGraphite** [meow-edit/meow#494]
Is there any option that makes meow show the keypad description after typing "?" key in the keypad state instead of automatically showing the description after a delay? I'm trying to simulate the Emacs native way of showing key help info, which allows you to input the prefix keys and then a "?" key to list available keys.

By the way, what is the correct way to define prefix keymap with `meow-leader-define-key`? If I do
```emacs-lisp
(meow-leader-define-key
  `("a" . ,my-prefix-map))
```
I cannot see the keymap name in keypad description (it's reasonable). However, if I do
```emacs-lisp
(meow-leader-define-key
  '("a" . my-prefix-map))
```
I can see the keymap name in keypad description, but when I type "SPC a", I will get error "a is undefined".

**Comment by DogLooksGood** [comment]
Currently, there's no builtin way to trigger description with a key, but you can set a custom function for keypad description.
This is the [code for which-key integration](https://github.com/meow-edit/meow/blob/master/meow-shims.el#L239).
To implement what you described, you can modify this function, do not show which-key immediately, unless a key press(use [set-transient-map](https://www.gnu.org/software/emacs/manual/html_node/elisp/Controlling-Active-Maps.html#index-set_002dtransient_002dmap) to bind this key temporarily)

For your second question,
Define an alias for your custom keymap, then use symbol.

```
(defvar my-prefix-map (make-keymap))
(defalias 'my-prefix-map my-prefix-map) // This line
(meow-leader-define-key
  `("a" . ,my-prefix-map))
```

This is how emacs builtin keymaps defined, e.g. vc-prefix-map, kmacro-map, etc.

**Comment by HardGraphite** [comment]
> Define an alias for your custom keymap, then use symbol.

Yes, it works!

> This is how emacs builtin keymaps defined, e.g. vc-prefix-map, kmacro-map, etc.

I read the definitions of `vc-prefix-map` and `kmacro-map`. I found they are defined with macro `defvar-keymap`, which can be expanded to `(defvar MAP-NAME (define-keymap ...))`. It seems that there is no alias defined. And code like `(meow-leader-define-key '("a" . vc-prefix-map) '("b" . kmacro-map))` does not work as well. I'm not sure if I misunderstood you.

In fact, I do not understand why a symbol cannot be used directly in `meow-leader-define-key`. `define-key` can accept a symbol as the command. I thought `meow-leader-define-key` might work the same way.

**Comment by DogLooksGood** [comment]
You will find `(defalias 'kmacro-keymap kmacro-keymap)` right after `defvar-keymap`.
