### ISSUE TITLE
Unintuitive cursor type behaviour

### ISSUE THREAD

**Issue by SpringerJack** [meow-edit/meow#496]
I used to wonder why `meow-cursor-type-region-cursor` seems to do nothing. I just hunted it down to this only being applied, if `meow-use-cursor-position-hack` being enabled. Is this intended behaviour? If so I'd like to mention this in its docstring.

**Comment by DogLooksGood** [comment]
`meow-use-cursor-position-hack` is considered deprecated.

**Comment by SpringerJack** [comment]
I see. Is `meow-cursor-type-region-cursor` deprecated aswell, since it seems to be used only in combination with that hack? If not I could still control the cursor shape during selection with `meow--redisplay-highlight-region-function`.

**Comment by DogLooksGood** [comment]
Yep, but I guess you don't want to custom cursor style during selection. There are some weird cases, if you use `bar` style cursor for selection.

**Comment by SpringerJack** [comment]
Alright. I was looking to fix in some themes I cannot distinguish between my cursor and the selected region. [Solarized](https://github.com/bbatsov/solarized-emacs/tree/master) would be an example of this. But I guess this is better solved by patching the affected themes then, thanks.
