### ISSUE TITLE
How to assign key chords?

### ISSUE THREAD

**Issue by alecStewart1** [meow-edit/meow#498]
Hello! I thought I'd check out Meow as in the past I used Evil.

I use the `helpful` package. By default it seems that `SPC h k` is bind to the default `describe-key` and same with `SPC h f` for `describe-function`.

How would I do key chords like this with Meow? Would I have to define a new state first? Having something like:

```emacs-lisp
(meow-leader-define-key
  '("h k" . helpful-key)
  '("h f" . helpful-function))
```

 Doesn't work, so I'm unsure as to what the recommended way of doing this is.

**Comment by DogLooksGood** [comment]
The functionality in meow is to enter keypad state.  In keypad state, keys are translated to simulate the key bindings with modifier keys.  So all you need to do is binding keys as without modal editing.

```
(define-key help-map "k" 'helpful-key)
(define-key help-map "f" 'helpful-function)
```

This will bind commands under `C-h`, which matches the input `SPC h`.  Please check the doc for how keypad works.

**Comment by DogLooksGood** [comment]
Please checkout [the doc of keypad](https://github.com/meow-edit/meow/blob/master/TUTORIAL.org#keypad)

**Comment by alecStewart1** [comment]
Ah, I see.
