### ISSUE TITLE
*Messages* buffer has meow-normal-mode and meow-motion-mode both enabled

### ISSUE THREAD

**Issue by drcxd** [meow-edit/meow#500]
The issue is described as the title. My related meow configuration is:
```
 (setq meow-mode-state-list
       '((special-mode . motion)
         (text-mode . normal)))
```
The package version is 20230801.37.

After Emacs has launched, I switched to the *Messages* buffer and found that meow-motion-mode and meow-normal-mode are both enabled. I think only the meow-motion-mode should be enabled. Is this a bug? How could I fix it?

**Comment by DogLooksGood** [comment]
Hey, I cannot reproduce in my side. What's your Emacs version? Do you switch the mode in other hooks?

**Comment by drcxd** [comment]
Hi, my Emacs version is 30.0.50. I tried to reproduce the issue with a clean Emacs setup. I installed meow 1.4.3. Then I executed `meow-global-mode` and the indicator in the mode line shows that both meow-motion-mode and meow-normal-mode is enabled.

**Comment by DogLooksGood** [comment]
Yep, I can reproduce.  I think it's a bug.

**Comment by drcxd** [comment]
Thanks, the fix works in my envrionment.
