### ISSUE TITLE
Space h f actually runs view-emacs-FAQ

### ISSUE THREAD

**Issue by jgarte** [meow-edit/meow#504]
Space h f actually runs `view-emacs-FAQ` instead of `describe-function`.

![image](https://github.com/meow-edit/meow/assets/47760695/02a5533a-1916-48e2-8ee6-347ea68d1a5b)

WDYT

**Comment by johannesneyer** [comment]
I have this in my config for these cases:
```elisp
(use-package emacs
  ; ...
  :bind
  (("C-h C-m". nil)
   ("C-h C-f". nil)
   ("C-h C-a". nil)))
```
