### ISSUE TITLE
About meow keypad mode

### ISSUE THREAD

**Issue by Prague2049** [meow-edit/meow#513]
After starting emacs, meow will enter meow keypad mode. Is it possible to set the mouse input method to rime English mode at the same time? Because every time I have to switch the Chinese input of rime to English, I can use the meow keypad mode command.

**Comment by DogLooksGood** [comment]
Meow wouldn't enter keypad mode automatically, unless you hit `SPC`.  If you are using system rime input method, you may want check out `smart-input-source` package.

**Comment by Prague2049** [comment]
Is it possible to enter insert mode when pressing the i key and the rime input method is Chinese? 
Is it the English input method for rime when pressing the ESC key to enter kaypad mode?

**Comment by DogLooksGood** [comment]
Which Rime you are using? The system Rime input method(e.g. Weasel, Squirrel, fcitx-rime) or emacs package `emacs-rime`?

**Comment by Prague2049** [comment]
My mac system Rime input is squirrel, and emacs package is emacs-rime.

**Comment by DogLooksGood** [comment]
You can disable emacs-rime for all non-insert modes
```
(setq rime-disable-predicates '(meow-normal-mode-p
                                meow-keypad-mode-p
                                meow-motion-mode-p
                                meow-beacon-mode-p))
```

**Comment by Prague2049** [comment]
Thank you very much! After pressing Esc, it did enter rime English input. After pressing i to enter insert mode, the input is still in English. Is it possible to enter Chinese input when pressing the I key?

**Comment by Prague2049** [comment]
what is the ascii mode ?
