### ISSUE TITLE
meow-back-symbol should not unconditionally reverse direction

### ISSUE THREAD

**Issue by politza** [meow-edit/meow#546]
Hey, great package !

In https://github.com/meow-edit/meow/blob/3247b9d4f2b46bcf8d216857a59d67dd416dcdb9/meow-command.el#L894 the direction is set to backward unconditionally.

This line is missing in the very similar implementation of meow-back-word: https://github.com/meow-edit/meow/blob/3247b9d4f2b46bcf8d216857a59d67dd416dcdb9/meow-command.el#L873 .

As  a result those motions are inconsistent. Moving backwards with meow-back-symbol moves to far, i.e. at the end of a selected symbol, it moves to the beginning of the previous one.

**Comment by DogLooksGood** [comment]
That's expected behavior, it depends on current selection type. When you have an expanding `word` selection, the `word` commands simply expand the selection.

https://github.com/meow-edit/meow/blob/master/EXPLANATION.org#selection

**Comment by DogLooksGood** [comment]
@Haxxflaxx They should be consistent, what you encountered?

**Comment by DogLooksGood** [comment]
Sorry for I didn't understand the issue in the first place.

Fixed dabfaaa
