### ISSUE TITLE
meow 应该搞个选项关闭keypad模式

### ISSUE THREAD

**Issue by 1925381584** [meow-edit/meow#548]
作者您好,
    首先很感谢你创造了这么好的按键模式,向你表示感谢. 不过关于keypad模式,我在使用中有一点不同想法想请你指教.如下:我感觉meow应该搞个选项关闭keypad模式,如果我想把它绑定到spc x m,我就直接绑了,我为什么要绑到C-x m,再把它转成spc x m呢?虽然它可以解决C-x C-x m这样多键序列的好处,但多键序列不是主流. 如果有了leader的加持, 基本可以把原本的多键序列转到leader下面. 但是因为有keypad这层转换,我就无法享受即使用C-c x m,又使用spc x m 的好处.我认为这个模式是让我少了一个选择. 并没有带来明显的好处. 以上是我个人的一点看法,希望没有冒犯到您.

**Comment by DogLooksGood** [comment]
你好，

Keypad 是一个独立的模式，通过命令 `meow-keypad` （默认绑定在 SPC）进入。你可以将其解绑或绑定任意其它的命令。

非侵入式的模式编辑是 Meow 的设计原则之一，使用 Emacs 内置功能并遵循 [Key Binding Convention](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html) 来构造自己的快捷键方案是推荐的做法。为模式编辑辑和非模式编辑各设计一套按键是冗余且没有必要的。

**Comment by 1925381584** [comment]
已经知道怎么解绑了, 再次表示感谢.
