### ISSUE TITLE
Number for meow-next-word aren't colored in emacsclient

### ISSUE THREAD

**Issue by Esnos33** [meow-edit/meow#568]
When emacs is opened with `emacsclient -c -a=""` there are no color around numbers, but if I open emacs with `emacs`, everything works. Using default theme.

![emacs](https://github.com/meow-edit/meow/assets/56300699/2c070efe-11c3-43d5-9ba8-4fbbe90f997e)
![emacsclient](https://github.com/meow-edit/meow/assets/56300699/c1b1c45c-d2d2-42f6-a20d-00e89ec3eda1)

**Comment by Esnos33** [comment]
@DogLooksGood Thanks for answer, but I don't use terminal version of emacs, only gui, and why does `meow-use-dynamic-face-color` would work different depending on if I open emacs via `emacs` or `emacsclient -c -a=""`? Trying to learn emacs.

**Comment by DogLooksGood** [comment]
Ah, sorry, I misunderstood your question. I can't reproduce with `emacsclient -c -a=""`. This is how it looks in my case. 

Do you have any theme related settings? How did your emacs server started, `emacs --daemon` vs `(server-start)`?
![image](https://github.com/meow-edit/meow/assets/11796018/cb74ab11-2ebc-4c00-9f8c-703a39d7d77b)

**Comment by Esnos33** [comment]
I just made test config where there is only meow setup and if I use `emacs --daemon` in terminal then `emacsclient -c` I don't have colors, but If I use `emacs` then `M-x server-start` or put `server-start` in config, then everything works. I'm using arch linux on sway, and my emacs version is 29.2 if that helps.

**Comment by Esnos33** [comment]
I think I will just use `emacs` with (server-start) in config. I still can't autostart emacs with sway, because emacs on autostart from systemd don't see .bashrc and can't find agda related stuff. I'm telling this, because I just wanted to say this isn't big deal, opening emacs from terminal and then using client, but this isn't smoothest first emacs experience. If not for meow, I wouldn't use emacs at all, so for me you made big difference DogLooksGood, thanks.

**Comment by YardQuit** [comment]
I have the same issue with the emacsclient. Does anyone know if this is an Emacs issue or is this an issue belonging to this project?
