### ISSUE TITLE
How to remove mathing parentheses?

### ISSUE THREAD

**Issue by Esnos33** [meow-edit/meow#573]
Hi, how can I remove matching parentheses in meow/vanilla emacs way? In helix you could delete matching parentheses by `md(`.
![image](https://github.com/meow-edit/meow/assets/56300699/168d5e2c-d352-4021-a3fe-4ec0513c1542)
![image](https://github.com/meow-edit/meow/assets/56300699/45e5a089-8f84-48a4-982c-4750d27e7cd2)

**Comment by Esnos33** [comment]
You can use https://github.com/Fuco1/smartparens, but is there some trick with `,` or `.` that have same functionality?

**Comment by DogLooksGood** [comment]
Emacs has a lot packages for parentheses manipulation, they are very powerful . So just use smartparens or any other option.

You can also do it with `inner`, `r`, `kill`, `block`, `replace`.
