### ISSUE TITLE
`Backspace` key delete region not work, Bug or Design?

### ISSUE THREAD

**Issue by sawyerzheng** [meow-edit/meow#574]
when I enable `meow-global-mode` , `backspace` key will cannot delete selected region any more. Is it a bug, or just a design on purpose.

When I disable  `meow-global-mode` , `backspace` will can delete region again.

**Comment by sawyerzheng** [comment]
Get it, thanks.

**Comment by tamwile** [comment]
Would it be possible to reactivate delete-active-region when we are in insert mode ?

I tried something like that:
`  (meow-disable-mode-hook . (lambda () (setq delete-active-region t)))
  (meow-insert-mode-hook . (lambda () (setq delete-active-region t)))
  (meow-insert-exit-hook . (lambda () (setq delete-active-region nil)))
  (meow-normal-mode-hook . (lambda () (setq delete-active-region nil)))`

But it's only partially working.
When i move the cursor inside an sexp, moving past the opening round bracket, the value of delete-active-region goes back to nil, even though i am in insert mode.
