### ISSUE TITLE
SPC SPC errors in meow-motion-mode

### ISSUE THREAD

**Issue by velppa** [meow-edit/meow#579]
Some time ago {SPC SPC} in `meow-motion-mode` stopped working. I'm using it in Magit to check the contents of commit, need to turn off meow for that.

I reproduced it with `emacs -Q`, downloading v1.4.5 from Non-GNU Elpa (Github releases lists latest release as v1.4.3 for some reason).

It looks like something's wrong with `H-SPC`.

```emacs-lisp
(package-initialize)
(package-install 'meow)
(require 'meow)
(meow-global-mode +1)
(toggle-debug-on-error)
(dired ".")
;; {SPC SPC} ;; Wrong type argument: commandp, 1
```

Debugger:

```
(wrong-type-argument commandp 1)
  call-interactively(1)
  #f(compiled-function () (interactive nil) #<bytecode -0x1c939b9cc8dff51c>)()
  funcall-interactively(#f(compiled-function () (interactive nil) #<bytecode -0x1c939b9cc8dff51c>))
  meow--execute-kbd-macro("H-SPC")
  meow-dispatch_7()
  funcall-interactively(meow-dispatch_7)
  meow--keypad-try-execute()
  meow-keypad-self-insert()
  funcall-interactively(meow-keypad-self-insert)
```

I'm on macOS (M1), tried different builds (emacs-mac-port, emacs-builds), all show the same behaviour.

**Comment by DogLooksGood** [comment]
Yep, I can reproduce.
