### ISSUE TITLE
feature request: ability to customize the keypad hints font

### ISSUE THREAD

**Issue by jsbmg** [meow-edit/meow#586]
Thank you very much for this excellent package!

I have a very minor issue - I use a variable pitch font in Emacs. This causes the keypad suggestions in the minibuffer to be misaligned. However, it seems that it's not possible to customize the face that displays the keypad hints. This is possible to do with other faces that are problematic when using a variable pitch font, for example `org-table` in `org-mode`, and various faces in the `which-key` package. It would be nice if meow exposed a face or faces in order to customize this font. 

![2024-04-28-000056_3816x304_scrot](https://github.com/meow-edit/meow/assets/63313743/f1d97b21-5387-4eed-9dc2-bb5c2e8c4c24)

**Comment by eshrh** [comment]
This is something we should add, but if you have which-key installed, meow should be using which key (and so you can customize the faces there).

**Comment by jsbmg** [comment]
Cool, thanks for the tip.
