### ISSUE TITLE
insert mode i and a do the same thing

### ISSUE THREAD

**Issue by bochy992** [meow-edit/meow#603]
they both insert before the character

**Comment by james-nesbitt** [comment]
if you have a range selected, i should enter edit-mode with the cursor at the beginning of the selection; a should enter edit-mode with the cursor at the end of the selection.
Please confirm that the above described behaviour is NOT what you get.

i and a exhibit the same behaviour is there is no selection.

**Comment by Esnos33** [comment]
This is intended, see  https://github.com/meow-edit/meow/discussions/87
