### ISSUE TITLE
Cannot bind <tab> in keypad

### ISSUE THREAD

**Issue by tbdcit** [meow-edit/meow#610]
The following does not seem to work

```
(meow-leader-define-key
 '("TAB" . meow-last-buffer)
 '("<tab>" . meow-last-buffer))
```

I have `(setq meow-keypad-leader-dispatch "C-c")` and `C-c <tab>` works as expected, but `<space> <tab>` does not.

**Comment by eshrh** [comment]
I can't reproduce this; your code works for me. Would you post your whole config somewhere?

**Comment by tbdcit** [comment]
It seems that the problem is only in modes that bind "C-c TAB". In org-mode for example: `describe-key "C-c TAB"` reports `meow-last-buffer` but `meow-keypad-describe-key TAB` reports `org-ctrl-c-tab`.

The meow part of my config can be found here: https://purple-noell-46.tiiny.site.

**Comment by xevrem** [comment]
> I can't reproduce this; your code works for me. Would you post your whole config somewhere?

binding `TAB` or `<tab>` in meow's `meow-leader-define-key` appears to only work as expected in GUI mode. In terminal mode, it fails; as it doesn't seem to properly resolve `TAB` and `<tab>`, instead falling back to whatever the self-insert-command resolve to... looking at the code for `meow-keypad`, it appears to explicitly ignore terminal local maps in lieu of gui local maps.

**Comment by DogLooksGood** [comment]
The same with #645
