### ISSUE TITLE
`SPC a` inserts an `a`

### ISSUE THREAD

**Issue by willbush** [meow-edit/meow#625]
According to the [tutor](https://github.com/meow-edit/meow/blob/bf595c7f464ebf6c653e9c0678e9df2e292cec12/meow-tutor.el#L588):

> Press SPC a, call the command on C-c a, which is
 undefined by default.

`SPC c a` works though.

Emacs version I'm using:
> GNU Emacs 31.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.43, cairo version 1.18.0)

**Comment by eshrh** [comment]
Try this? https://github.com/meow-edit/meowissues/583#issuecomment-2052106006

i can't reproduce... it works on my emacs with no packages installed.

**Comment by willbush** [comment]
Thanks for the fast reply! `(setq meow-keypad-leader-dispatch "C-c")` fixed it!

Not sure what is going wrong. I also tried removing all my settings and packages only installing meow. Also tried Emacs 29.4. was trying it in the scratch buffer and meow-tutor.
