### ISSUE TITLE
Is it possible to make "meow-next-word-expand"?

### ISSUE THREAD

**Issue by Esnos33** [meow-edit/meow#640]
Hi, currently there isn't command that extends current selection by word when didn't start in with word type. There are only commands that universally expands by char, line, find and block, but there is nothing for word, which would be useful.

**Comment by Esnos33** [comment]
Also, is it possible to add expand with `meow-visit` or with any other search feature? When I try to use `set-mark-command`, then meow-visit, it doesn't expand.

**Comment by Esnos33** [comment]
I just found out you can use isearch and forward word for my use-case. If you know how to do it from meow please tell me, but for now I will map normal emacs functions to meow keymap

**Comment by DogLooksGood** [comment]
You can always expand the region with built-in emacs command. For word, you can use `M-f` and `M-b`.

> Also, is it possible to add expand with meow-visit or with any other search feature? When I try to use set-mark-command, then meow-visit, it doesn't expand.

And yes, isearch is perfect for this.

**Comment by Esnos33** [comment]
I needed to make kmacro in which I couldn't know how much to expand with number. I solved problem by learning more about mark, isearch and backward-word and forward-word (which I mapped to B and E in meow layout). Again, thanks for answer, this is great package and more and more I appreciate how nicely it works with default emacs bindings.
