### ISSUE TITLE
What's up with meow-repeat?

### ISSUE THREAD

**Issue by attilakv** [meow-edit/meow#642]
The `VIM_COMPARISON.org` lists vims repeat equivalent to be `meow-repeat`, but there is no such command.

The example configurations for colemak, dvorak, dvp and qwerty all use the builtin `repeat` command, but that is not an equivalent at all, as it can only repeat movement and mode switching.

I love that feature in vim. Is it still planned?

**Comment by DogLooksGood** [comment]
Hey,

I think we won't have the repeat like Vim does. As we do movement first, there's no clear boundary that we can use to identify an atomic operation for repeating. 

Suggestions are welcomed.

**Comment by attilakv** [comment]
Hello,

If I understand the problem correctly, the movement is manipulating the region, and actions are executed on that region. So actions cannot be recorded with the "logical region" it acted on? (aka line, word, defun, etc.)

In that case the `meow-repeat` doesn't have to be 1-to-1 equivalent. Just record any editing action, and it's result, and when the user wants to `meow-repeat`, they will redo the most recent action on the then selected region or on the cursor. This would be a bit more annoying than vim, but it could be called an equivalent.

It could also be possible (though depending on the implementation incredibly difficult) to record the selection, the action and it's result separately, and combine them after the action is done (or when `meow-repeat` is called).
I am not familiar with the codebase, so I can't say whether it would worth the effort, but it would be a 1-to-1 equivalent

**Comment by okamsn** [comment]
Of the existing solutions, one option is to create a keyboard macro from recent key presses using `kmacro-edit-lossage`. Editing keyboard macros saw some improvements in Emacs 30.

**Comment by DogLooksGood** [comment]
Hey, 

First, it's totally possible to record the selection operations. But most movements in meow create/manipulate a selection, and how the commands are designed is based on a concept that you almost never have to cancel the selection before you do something.  It's totally fine to have a selection all the time while you are moving here and there. With this consideration in mind, we don't know where to start recording.

Second, to record something and replay it later, it's done by the kmacro in Emacs. You have this feature builtin, and meow has several features on top of kmacro, for example, the BEACON state.  It's still different from the repeat in vim.

And if you want to replace a few symbols quickly, there's one way to do it with `mark - change - <edit> - ESC - save - search - replace - search - replace ...`.

**Comment by attilakv** [comment]
I see, should have guessed there is a reason no one complained about this 😅.

Regarding your second point: I wasn't familiar with macros, so I probably over complicated things. I apologize.

As for the first point: thanks for clarifying. Is it possible to record all the time, and restart the recording when the current selection is "overruled"? That's what I was assuming in my second suggestion, but even it it's possible, I think that would require modifying all movement functions. That's why I am not sure it would be worth it.

But in the end, replacing a few symbols quickly is ultimately what I've been looking for, thanks 🙂. But I've only learned from your answer, that `meow-change` selects the edited text after exit. Is this documented anywhere? Why does `meow-insert` not do it?

**Comment by DogLooksGood** [comment]
Have recording all the time may not be a good idea, as I don't want to introduce another "macro" system in meow. We'd better focus on some enhancements on top of Emacs builtin features. But I haven't read anything about the kmacro improvements which @okamsn mentioned, maybe there are some facilities we can use to keep it simple.

There's a variable that controls this behavior, `meow-select-on-change`. You will have a region for `meow-change`, that's why we can track it.
