### ISSUE TITLE
How to substract from selection

### ISSUE THREAD

**Issue by JulienMalka** [meow-edit/meow#648]
Hello, new to meow here so I don't know if the feature is not there or if I am not reading documentation like I should, but a pretty natural thing I want to often do is:
1. Select a few (let's say 4) lines
2. Remove some words from selection

My natural take to that would be to do xxxx and then some command to remove a word from the end of the selection, but I did not find such a command. Does it not exists ?
Thanks

**Comment by DogLooksGood** [comment]
Hey, 
First of all, Emacs builtin commands are still all available, there's nothing preventing you from manipulating regions.

However the idea from Meow is, when you want to move, you identify the target position by its type. In your example, you probably don't want to select some lines then adjust with words, instead you want to select to an end of a word directly. The right way is to start with `next-word` or `next-symbol`, then expand with numbers.

In general, selection commands with mixed types are rarely used and they are not efficient.

**Comment by JulienMalka** [comment]
Understood, thanks.
