### ISSUE TITLE
Requesting for a Community space other than Github discussion

### ISSUE THREAD

**Issue by Absinthe8383** [meow-edit/meow#652]
Hello, There should  a community beside the github disscussion, because not all people are logged in github everytime and some even find it  bad (like me), There can be xmpp, matrix, irc, or even email list for discussions, please think about this about this.

Thank you for developing meow.

**Comment by DogLooksGood** [comment]
Hey, I'm good to any of this, just have no time working on it.  I appreciate if someone can help.

**Comment by contrapunctus-1** [comment]
A Meow user in the [Emacs XMPP channel](https://xmpp.link/#emacs@conference.conversations.im?join) saw this issue and created a [Meow XMPP channel](https://xmpp.link/#meow@chat.disroot.org?join).

They requested me to share this on their behalf, as they do not have a GitHub account.

The easiest way to join XMPP is to install Quicksy (libre and gratis) on your Android or iOS phone, then open the links above. For more information and other options, please see [The Quick and Easy Guide to XMPP](https://contrapunctus.codeberg.page/the-quick-and-easy-guide-to-xmpp.html)

**Comment by DogLooksGood** [comment]
Done, then I'm going to register and learn how to use it 😼
