### ISSUE TITLE
meow-inner-of-thing not work

### ISSUE THREAD

**Issue by oscar20200122** [meow-edit/meow#659]
1.emacs31.0.5版本下meow-inner-of-thing不起作用， region-active-p 函数返回false
2.如果buffer编辑过，或者鼠标点击了buffer, meow-inner-of-thing正常工作,region-active-p 函数返回true

**Comment by DogLooksGood** [comment]
I saw your discussion on emacs-china. As it's not related to meow, I'll close for now.
