### ISSUE TITLE
Cheatsheet 表现不正常

### ISSUE THREAD

**Issue by QuarterHeaven** [meow-edit/meow#66]
![image](https://user-images.githubusercontent.com/41909950/131212937-75e186be-2fd1-4ecc-9692-9dda44853bf0.png)
如图

**Comment by DogLooksGood** [comment]
在 `{` 和 `}` 键上面的命令是什么呢？看起来像是某个命令的名字影响了排布（虽然我不确定是哪个键）。还有就是看起来你这个 buffer 里面的字体是非等宽的。下面部分的表格看起来也没有对齐。

**Comment by QuarterHeaven** [comment]
> 在 `{` 和 `}` 键上面的命令是什么呢？看起来像是某个命令的名字影响了排布（虽然我不确定是哪个键）。还有就是看起来你这个 buffer 里面的字体是非等宽的。下面部分的表格看起来也没有对齐。

是直接 copy 的 KEYBINDING.md 中的 qwerty， `{` 与 `}` 应当是没有命令绑定的。
字体我看了一下，是Menlo。很遗憾，它的确是等宽字体。
我稍后换一个字体看看是否解决问题。

**Comment by QuarterHeaven** [comment]
![image](https://user-images.githubusercontent.com/41909950/131216660-b76a6b40-df53-404a-8d83-6dcfb4fd23ff.png)
更换为了 FiraCode, 仍然有这个问题.

**Comment by DogLooksGood** [comment]
像这个字符 `→` 在你那里并不是一个字符的宽。这个字符的范围也不在 Fira Code 中，应该是 fallback 之后的某个字体。这大概是下面不对齐的原因。

![image](https://user-images.githubusercontent.com/11796018/131219554-4c9f85b2-1efa-4588-86fe-42351307c8e9.png)

上面的地方我还不是很有头绪。

**Comment by QuarterHeaven** [comment]
![image](https://user-images.githubusercontent.com/41909950/131221206-2d9c7c57-9993-49de-be00-e9a7e014bab4.png)
箭头符号的话, 我使用的 FiraCode 是 Nerd Font 版本, 大部分图标 (包括箭头) 都是有的.
请问你使用的是什么字体? 我用你的字体试试.

**Comment by QuarterHeaven** [comment]
![image](https://user-images.githubusercontent.com/41909950/131221632-64ea2b48-aca6-4db9-8ef1-6e379cd57ca0.png)
我将所有 keybinding 删除了看, 发现确实应该是箭头的问题. 箭头似乎会把后面的符号吞掉.

**Comment by QuarterHeaven** [comment]
![image](https://user-images.githubusercontent.com/41909950/131221899-998619b5-a281-46b6-8a99-b29902557c6a.png)
将箭头用其他符号/字母代替, 可以解决.

**Comment by DogLooksGood** [comment]
我用的 JetBrains Mono，我也不知道里面有没有这个箭头。

**Comment by QuarterHeaven** [comment]
我发现问题所在了. 我将下图中光标的 9 改为 8, 输出的 cheatsheet 就如后图所示.
![image](https://user-images.githubusercontent.com/41909950/131224883-78e6cfed-cd4e-4498-9356-fce009eac870.png)
![image](https://user-images.githubusercontent.com/41909950/131224014-baef6e5e-ae55-4407-8f75-6587af1bb4c5.png)
我想会不会是某种原因导致含有箭头符号的字符串长度被误测导致多删除了几个字符?
另: 我新开了一个只加载了最新 meow 的 emacs, 该现象仍然存在.
![image](https://user-images.githubusercontent.com/41909950/131225342-9856a9ad-6a8b-497f-8fe0-5d47135347d4.png)

**Comment by QuarterHeaven** [comment]
JetBrains Mono 也存在这个问题, 应该和字体无关.

**Comment by DogLooksGood** [comment]
我从你的图中观察只要有箭头就会出现错位的情况。我觉得我们可以考虑用其它的方式替换箭头。比如说 `<-` `->` 这样的话应该就不存在这个问题了。

你用的是什么版本的 Emacs?

**Comment by QuarterHeaven** [comment]
![image](https://user-images.githubusercontent.com/41909950/131238786-e6ceede6-05fb-4323-b542-e3d245a28660.png)
是从 brew 下载的 emacs-plus.
左右箭头使用 `<-` `->` 是很好的选择, 我看 Readme 里的示意图就是这样的? 不过这样的话上下箭头可能不太好表示.

**Comment by DogLooksGood** [comment]
这个问题我觉得不是与字体相关，如果要修正可以通过修改 `meow-command-to-short-name-list` 。
先关闭了。
