### ISSUE TITLE
One minor problem in meow tutor 

### ISSUE THREAD

**Issue by Rope-a-dope** [meow-edit/meow#665]
On "MORE ON BEACON" part, if we follow the instruction then you can see there is also a fake cursor in front of -->.
And if we follow step 6, then the edits only apply to number 3.

![image](https://github.com/user-attachments/assets/6f266733-492f-471a-8321-b987da95df5c)

I had to type e to reduce selection, then edit, then just press G to cancel grab. There is the same example here [Explanation - Ways to multiedit - The answer from Meow](https://github.com/meow-edit/meow/blob/master/EXPLANATION.org), but obviously there is no "-->" here.
![image](https://github.com/user-attachments/assets/e930d923-e31e-4008-b642-6604f669fbf3)

**Comment by DogLooksGood** [comment]
I see, probably we should just say, select "1 2 3"?

**Comment by Rope-a-dope** [comment]
> I see, probably we should just say, select "1 2 3"?

It's your call. But I don't know what step 6 does, it doesn't seem to do anything. Maybe this needs to be updated?

**Comment by DogLooksGood** [comment]
I think it should be `ESC` or `<escape>` here.  The keys in tutor are interpolated based on your current keymap.  This is how it looks on my side.

![image](https://github.com/user-attachments/assets/05a01d49-187f-4004-a30f-eadcecce2101)

**Comment by Rope-a-dope** [comment]
> I think it should be `ESC` or `<escape>` here. The keys in tutor are interpolated based on your current keymap. This is how it looks on my side.
> 
> ![image](https://private-user-images.githubusercontent.com/11796018/384373974-05a01d49-187f-4004-a30f-eadcecce2101.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwODMzNTksIm5iZiI6MTczMTA4MzA1OSwicGF0aCI6Ii8xMTc5NjAxOC8zODQzNzM5NzQtMDVhMDFkNDktMTg3Zi00MDA0LWEzMGYtZWFkY2VjY2UyMTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDE2MjQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwNjNmMjhiZTIyZWJjNTQ5ZGVkYjdkODJhNjk0NTRkMmJiZWNlN2U2ZGI0MzY3NzFlMGYyNzVkNTlhYTQ5MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.x_KitEwvneZbXoeQY7MGv8g1cfFeE0-cVnVLAgU8nZw)

Yes, that is how I did it.

**Comment by Rope-a-dope** [comment]
I see this is updated. Thank you so much
