### ISSUE TITLE
Change 'a' when no selection active

### ISSUE THREAD

**Issue by leath-dub** [meow-edit/meow#685]
one of the things that surprised me was that while a and i insert after and before for selections, when no selection is active 'a' is the same as 'i'. I think this is redundant and it would be more useful to have 'a' insert after current cursor.

**Comment by DogLooksGood** [comment]
We have this in FAQ, and here's the content for reference: https://github.com/meow-edit/meow/discussions/87

Of course you can implement your own append command, I would not recommend to do so.

**Comment by leath-dub** [comment]
> We have this in FAQ, and here's the content for reference: #87
> 
> Of course you can implement your own append command, I would not recommend to do so.

Ahh sorry I missed that, that makes sense.
