### ISSUE TITLE
Potential reference to non-existent(?) functions

### ISSUE THREAD

**Issue by gs-101** [meow-edit/meow#697]
https://github.com/meow-edit/meow/blob/f74017c172167edbe15bf7a922a6313c7aa848bd/meow-command.el#L1565

Sorry if I'm missing some context of the functionality of `last-command`, but wouldn't the correct version of this line be:

```diff
-  (unless (member last-command '(meow-pop-to-mark-command meow-unpop-to-mark-command))
+  (unless (member last-command '(meow-pop-to-mark meow-unpop-to-mark))
```
Since these commands don't have the `-command` suffix as part of their name?

**Comment by lostCat-31159** [comment]
I just started using Meow and was wondering why `meow-pop-to-mark` was clogging up the mark-ring with duplicates.
This fixed it for me.

**Comment by gs-101** [comment]
> [...] This fixed it for me.

Great, I think I'll make a PR right now, I was waiting for #690 to be merged to make one as to not cause any issues.
