### ISSUE TITLE
Is it possible to add a description to prefix keys in keypad?

### ISSUE THREAD

**Issue by bsag** [meow-edit/meow#71]
First, thanks for writing meow! I'm really enjoying how powerful and streamlined it is.

I've created a few top-level items using `meow-leader-define-key`, some of which I've built with a letter prefix to group similar commands together, e.g.:

```
   '("w w" . ace-window)
   '("w u" . winner-undo)
   '("w r" . winner-redo)
   '("w h" . split-window-below)
   '("w v" . split-window-right)
   '("w c" . delete-window)
   '("w o" . delete-other-windows)
```

This works well, enabling me to press `SPC w u` for winner undo for example, but at the top level menu, the 'w' prefix is just labelled `+prefix`. 

Is there some way I am missing to provide a more descriptive label like "windows"? I know that you can do that with which-key, but I'm not sure how to do that when meow is providing the items.

Thanks for any help you can provide!

**Comment by DogLooksGood** [comment]
Here's an example if you are using KEYPAD mode.

```
(defvar window-keymap
  (let ((keymap (make-keymap)))
    (define-key keymap (kbd "w") #'ace-window)
    (define-key keymap (kbd "u") #'winner-undo)
    (define-key keymap (kbd "r") #'winner-redo)
    (define-key keymap (kbd "h") #'split-window-below)
    (define-key keymap (kbd "v") #'split-window-right)
    (define-key keymap (kbd "c") #'delete-window)
    (define-key keymap (kbd "o") #'delete-other-windows)
    keymap))

;; define an alias for your keymap
(defalias 'window-keymap window-keymap)

(global-set-key (kbd "C-x C-w") 'window-keymap)
;;                              ^ note the quote
```

Then in KEYPAD popup, it will be displayed as `+window-keymap`.

I think the alias way is the built-in way in Emacs, [how kmacro-keymap is defined in emacs source code](https://github.com/emacs-mirror/emacs/blob/3af9e84ff59811734dcbb5d55e04e1fdb7051e77/lisp/kmacro.el#L203).

---

But if you define your keys in leader, there's no key description. The popup description in Meow is only for KEYPAD. The reason is leader is designed to be simple, since the shortcuts in leader is not baked by a normal key binding, it is not recommended to have complex keymap in leader.

If you want `SPC w ?`, you should define `C-w ?`, and add `'("w" . meow-keypad-start)` in leader.

---

And `C-w` is `kill-region` by default, you should not overwrite it, since it is used by Meow. If you do, remember to binding `kill-region` to another key, and set `meow--kbd-kill-region`.

Maybe `C-o` is a good option.

---

Feel free to ask if this is not clear to you.

**Comment by bsag** [comment]
Defining the keymap as you describe definitely sounds like the best way to do it. And thanks for reminding me that C-w is bound to kill-region - I definitely need to change that binding!! I previously used evil, so I tend to forget about the basic Emacs keybindings.

Thanks for the help!

**Comment by joelpet** [comment]
I have a rather extensive and, in some places, deep keymap tree, heavily inspired by the Spacemacs default bindings. Below is the code I use to set up prefix keymaps with descriptions that `which-key` recognizes.

Do you see any issues or significant drawbacks with this approach compared to the one suggested in https://github.com/meow-edit/meow/issues/71#issuecomment-962090002? Specifically, I’m unclear about the purpose of `(defalias 'window-keymap window-keymap)` in the suggested code. Could omitting it lead to unexpected behavior?

```elisp
(mapc
   (lambda (elt)
     (let ((keymap (current-global-map))
           (key (car elt))
           (def (cdr elt)))
       (define-key keymap (kbd key) (cons def (make-sparse-keymap)))))
   '(("C-c a" . "applications")
     ("C-c a e" . "email")
     ("C-c a e n" . "notmuch")
     ("C-c a o" . "org")
     ("C-c a o d" . "drill")
     ("C-c a o f" . "feed")
     ("C-c a o C" . "clock")
     ("C-c a o r" . "roam")
     ("C-c a o r d" . "dailies")
     ("C-c a o r t" . "tags")
     ("C-c a o w" . "web")
     ("C-c a p" . "pass")
     ("C-c a t" . "terminal")
     ("C-c a t s" . "shell")
     ("C-c b" . "buffers")
     ("C-c e" . "errors")
     ("C-c e f" . "flymake")
     ("C-c e f b" . "backends")
     ("C-c f" . "files")
     ("C-c f d" . "chezmoi")
     ("C-c f e" . "emacs")
     ("C-c i" . "insertion")
     ("C-c j" . "jump|join|split")
     ("C-c k" . "major mode commands")
     ("C-c l" . "layouts")
     ("C-c p" . "projects")
     ("C-c p s" . "search")
     ("C-c p x" . "execute")
     ("C-c q" . "quit")
     ("C-c r" . "registers|rings|resume")
     ("C-c s" . "search|symbol")
     ("C-c s a" . "ag")
     ("C-c s g" . "grep")
     ("C-c s k" . "ack")
     ("C-c s r" . "ripgrep")
     ("C-c t" . "toggles|themes")
     ("C-c v" . "vc|git")
     ("C-c v f" . "files")
     ("C-c w" . "windows")
     ("C-c z" . "text")
     ("C-c z a" . "align")
     ("C-c z l" . "lines")))
```

Thank you for creating such an excellent package as Meow!

**Comment by DogLooksGood** [comment]
@joelpet I see, I don't think there's anything wrong with your method. `defalias` is not necessary, it doesn't matter how you construct your key binding. I just use `defalias` to create an alias for a keymap, but I think this method works as well.
