### ISSUE TITLE
Error on open cheatsheet when use key alias in meow-normal-define-key

### ISSUE THREAD

**Issue by 404cn** [meow-edit/meow#75]
Like title says, it worked but can not run `meow-cheatsheet`.

```emacs-lisp
(meow-normal-define-key
     '("s" . "C-s"))
```
<img width="1003" alt="Screen Shot 2021-11-28 at 3 16 35 PM" src="https://user-images.githubusercontent.com/24653356/143733419-62011e13-06d3-41c2-8920-4f516383dc70.png">

OS: macOS 12.0.1
Emacs: emacs-app-nightly: 2021-11-26.9721dcf.master
Meow: latest

**Comment by DogLooksGood** [comment]
reproduced.

**Comment by DogLooksGood** [comment]
最近的补丁中修复了错误的问题，但是当前的实现中这里是个 compiled function, 所以只能先显示为空。
