### ISSUE TITLE
ielm bug

### ISSUE THREAD

**Issue by bdarcus** [meow-edit/meow#78]
`ielm` is not working correctly for me ATM.

When I open it, it looks like it's in normal mode.

![image](https://user-images.githubusercontent.com/1134/144051899-36c0c7e6-1738-4d7e-ab0a-57d1aceeeb66.png)

If I type `i`, the cursor does not change, and the character `i` is inserted at the ielm prompt.

But if I then type `k`, the cursor moves up as in normal mode.

**Comment by DogLooksGood** [comment]
I think you are in motion mode. 

```
(add-to-list 'meow-mode-state-list '(comint-mode . normal))
```

For all REPL, normal mode should be used. 

Do not exclude `meow` from any mode, if you do that, you have are losing the way to start keypad state.

**Comment by bdarcus** [comment]
Thanks!

**Comment by DogLooksGood** [comment]
fixed in 427272d 
Use normal state for `comint-mode` by default.

**Comment by bdarcus** [comment]
Followup, not worth an issue:

Why does `meow-expand-exclude-mode-list` include markdown and org by default?

**Comment by DogLooksGood** [comment]
@bdarcus 

Inline position hint is displayed as overlay. It's common to use variable pitch, or variable font sizes in org and markdown.
So overlays will mess up displays.

![Peek 2021-12-01 00-45](https://user-images.githubusercontent.com/11796018/144090190-d9806d67-7732-4e96-8e58-3bfcbba56fc1.gif)

**Comment by bdarcus** [comment]
Gotcha; so if I'm using fixed-width consistently I may as well set it nil?
