### ISSUE TITLE
Can't remap meow-keypad-ctrl-meta-prefix

### ISSUE THREAD

**Issue by krdzo** [meow-edit/meow#79]
Hi. Trying out meow and couldn't change prefix for `C-M-`.
I tried it even on stock emacs only with `straight.el` and `use-pakcage` installed. This is my configuration:
```
(use-package meow
  :config
  (setq meow-keypad-ctrl-meta-prefix ?a)
  (meow-setup)
  (meow-global-mode 1))
```

 `meow-setup` function is copied from [default qwerty setup](https://github.com/meow-edit/meow/blob/master/KEYBINDING_QWERTY.org)

**Comment by DogLooksGood** [comment]
Hi, It's required to bind `a` in leader keymap as `meow-keypad-start`.

```
(meow-leader-define-key
 '("a" . meow-keypad-start)
 ...)
```

If you use `a` for `C-M-`, Keybindings like `C-x C-a` become not accessible.

`m` is used, because `C-m` is `RET`, so there's no `C-m`.
`g` is used, because `C-g` is `keyboard-quit`, so there's no `C-g`.

How about `i`, for `C-i` is `TAB`.

**Comment by krdzo** [comment]
Aha. Thanks for the explanation. 
Didn't occur to me to bind it in the `meow-leader-keymap` I thought that only changing `meow-keypad-ctrl-meta-prefix` variable was enough. Maybe add a note about that [here](https://github.com/meow-edit/meow/blob/master/CUSTOMIZATIONS.org#meow-keypad-ctrl-meta-prefix) or somewhere else in the documentation.

> If you use a for C-M-, Keybindings like C-x C-a become not accessible.
>
> m is used, because C-m is RET, so there's no C-m.
> g is used, because C-g is keyboard-quit, so there's no C-g.
>
> How about i, for C-i is TAB.

I will think about this. The `a` was just a example because I didn't think it thru enough, just wanted for `g` not to be occupied but after reading why you bound `g` as `C-M-` I will probably move my `SPC g` binging somewhere else and leave the default binding be. 

P.S. Is it appropriate to write here for questions that are not specifically issue related? For example I would like to disable, or just show less items, of the numbers overlay when `meow-[next|back]-word` is invoked but can't find a way to do it. I have many such small questions/feature ideas but don't want to flood the issue tracker with them if that is a problem.

**Comment by DogLooksGood** [comment]
Yes, I think here is the good place for questions.

Currently, there's no way to disable numbers overly for `meow-[next|back]-word`. Consider it a feature, I can add one.

**Comment by krdzo** [comment]
Thank you for this. 
Yesterday and today I tried to use the overlay a little bit more than before and it isn't as distracting when you get used to it. So I had a change of hart on the overlay but it will help somebody for sure.
