### ISSUE TITLE
Integrating with the general package

### ISSUE THREAD

**Issue by KaranAhlawat** [meow-edit/meow#96]
Hello,

I have general setup with some prefix keys and mappings i like to keep handy the way I have them setup. But using meow (and disabling evil-mode) seems to also take down those keybinds.

Is this intended? Or is there a workaround, or some configuration I must setup?

Regards,
Karan

**Comment by DogLooksGood** [comment]
Hi, 

One design principle for meow is to avoid complex keymap. 
Usually, you don't bind a lot keys in meow's leader keymap, you just bind keys like `C-c C-c` and execute it via keypad state.

For example, if you can have commands bind via __whatever tools__
- test-buffer `C-c t b`
- test-project `C-c t p`
- test-function `C-c t c`

Then though the keypad state, you can execute them via `SPC c t b`, `SPC c t p` and `SPC c t c`.

---
We use [Discussion](https://github.com/meow-edit/meow/discussions) for questions and ideas.

Feel free to ask anything there if it doesn't make sense to you.
