### ISSUE TITLE
Better documentation for beacon mode

### ISSUE THREAD

**Issue by Not-Leader** [meow-edit/meow#98]
Meow's `beacon-mode` appears to be an incredibly powerful multiedit feature, though the issue is that I'm not sure how to use. Perhaps a BEACON.org file may be helpful here, in order to minimise confusion.

**Comment by DogLooksGood** [comment]
Hi,
We have some [examples](https://github.com/meow-edit/meow/blob/master/EXPLANATION.org#the-answer-from-meow) here.

I also made a [3 minute video](https://github.com/meow-edit/meow/discussions/97) to explain beacon state, but sorry for my bad english.

**Comment by DogLooksGood** [comment]
close in favor of meow-tutor is added.
